// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/store/models/externalloginuser"
)

// ExternalLoginUser is the model entity for the ExternalLoginUser schema.
type ExternalLoginUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// LoginSourceID holds the value of the "login_source_id" field.
	LoginSourceID int64 `json:"login_source_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// NickName holds the value of the "nick_name" field.
	NickName string `json:"nick_name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// AccessTokenSecret holds the value of the "access_token_secret" field.
	AccessTokenSecret string `json:"access_token_secret,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// ExpiredAt holds the value of the "expired_at" field.
	ExpiredAt    time.Time `json:"expired_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalLoginUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalloginuser.FieldID, externalloginuser.FieldUserID, externalloginuser.FieldLoginSourceID:
			values[i] = new(sql.NullInt64)
		case externalloginuser.FieldExternalID, externalloginuser.FieldProvider, externalloginuser.FieldEmail, externalloginuser.FieldName, externalloginuser.FieldFirstName, externalloginuser.FieldLastName, externalloginuser.FieldNickName, externalloginuser.FieldDescription, externalloginuser.FieldAvatarURL, externalloginuser.FieldLocation, externalloginuser.FieldAccessToken, externalloginuser.FieldAccessTokenSecret, externalloginuser.FieldRefreshToken:
			values[i] = new(sql.NullString)
		case externalloginuser.FieldExpiredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalLoginUser fields.
func (elu *ExternalLoginUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalloginuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			elu.ID = int(value.Int64)
		case externalloginuser.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				elu.ExternalID = value.String
			}
		case externalloginuser.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				elu.UserID = value.Int64
			}
		case externalloginuser.FieldLoginSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field login_source_id", values[i])
			} else if value.Valid {
				elu.LoginSourceID = value.Int64
			}
		case externalloginuser.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				elu.Provider = value.String
			}
		case externalloginuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				elu.Email = value.String
			}
		case externalloginuser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				elu.Name = value.String
			}
		case externalloginuser.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				elu.FirstName = value.String
			}
		case externalloginuser.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				elu.LastName = value.String
			}
		case externalloginuser.FieldNickName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nick_name", values[i])
			} else if value.Valid {
				elu.NickName = value.String
			}
		case externalloginuser.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				elu.Description = value.String
			}
		case externalloginuser.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				elu.AvatarURL = value.String
			}
		case externalloginuser.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				elu.Location = value.String
			}
		case externalloginuser.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				elu.AccessToken = value.String
			}
		case externalloginuser.FieldAccessTokenSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_secret", values[i])
			} else if value.Valid {
				elu.AccessTokenSecret = value.String
			}
		case externalloginuser.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				elu.RefreshToken = value.String
			}
		case externalloginuser.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				elu.ExpiredAt = value.Time
			}
		default:
			elu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalLoginUser.
// This includes values selected through modifiers, order, etc.
func (elu *ExternalLoginUser) Value(name string) (ent.Value, error) {
	return elu.selectValues.Get(name)
}

// Update returns a builder for updating this ExternalLoginUser.
// Note that you need to call ExternalLoginUser.Unwrap() before calling this method if this ExternalLoginUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (elu *ExternalLoginUser) Update() *ExternalLoginUserUpdateOne {
	return NewExternalLoginUserClient(elu.config).UpdateOne(elu)
}

// Unwrap unwraps the ExternalLoginUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (elu *ExternalLoginUser) Unwrap() *ExternalLoginUser {
	_tx, ok := elu.config.driver.(*txDriver)
	if !ok {
		panic("models: ExternalLoginUser is not a transactional entity")
	}
	elu.config.driver = _tx.drv
	return elu
}

// String implements the fmt.Stringer.
func (elu *ExternalLoginUser) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalLoginUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", elu.ID))
	builder.WriteString("external_id=")
	builder.WriteString(elu.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", elu.UserID))
	builder.WriteString(", ")
	builder.WriteString("login_source_id=")
	builder.WriteString(fmt.Sprintf("%v", elu.LoginSourceID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(elu.Provider)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(elu.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(elu.Name)
	builder.WriteString(", ")
	builder.WriteString("first_name=")
	builder.WriteString(elu.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(elu.LastName)
	builder.WriteString(", ")
	builder.WriteString("nick_name=")
	builder.WriteString(elu.NickName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(elu.Description)
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(elu.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(elu.Location)
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(elu.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("access_token_secret=")
	builder.WriteString(elu.AccessTokenSecret)
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(elu.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("expired_at=")
	builder.WriteString(elu.ExpiredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExternalLoginUsers is a parsable slice of ExternalLoginUser.
type ExternalLoginUsers []*ExternalLoginUser
