// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/store/models/oauth2grant"
	"github.com/gitbundle/server/store/models/predicate"
)

// Oauth2GrantDelete is the builder for deleting a Oauth2Grant entity.
type Oauth2GrantDelete struct {
	config
	hooks    []Hook
	mutation *Oauth2GrantMutation
}

// Where appends a list predicates to the Oauth2GrantDelete builder.
func (od *Oauth2GrantDelete) Where(ps ...predicate.Oauth2Grant) *Oauth2GrantDelete {
	od.mutation.Where(ps...)
	return od
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (od *Oauth2GrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, od.sqlExec, od.mutation, od.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (od *Oauth2GrantDelete) ExecX(ctx context.Context) int {
	n, err := od.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (od *Oauth2GrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauth2grant.Table, sqlgraph.NewFieldSpec(oauth2grant.FieldID, field.TypeInt))
	if ps := od.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, od.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	od.mutation.done = true
	return affected, err
}

// Oauth2GrantDeleteOne is the builder for deleting a single Oauth2Grant entity.
type Oauth2GrantDeleteOne struct {
	od *Oauth2GrantDelete
}

// Where appends a list predicates to the Oauth2GrantDelete builder.
func (odo *Oauth2GrantDeleteOne) Where(ps ...predicate.Oauth2Grant) *Oauth2GrantDeleteOne {
	odo.od.mutation.Where(ps...)
	return odo
}

// Exec executes the deletion query.
func (odo *Oauth2GrantDeleteOne) Exec(ctx context.Context) error {
	n, err := odo.od.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauth2grant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (odo *Oauth2GrantDeleteOne) ExecX(ctx context.Context) {
	if err := odo.Exec(ctx); err != nil {
		panic(err)
	}
}
