// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/gitbundle/store/models/oauth2applicationcode"
	"github.com/gitbundle/gitbundle/store/models/predicate"
)

// Oauth2ApplicationCodeUpdate is the builder for updating Oauth2ApplicationCode entities.
type Oauth2ApplicationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *Oauth2ApplicationCodeMutation
}

// Where appends a list predicates to the Oauth2ApplicationCodeUpdate builder.
func (ocu *Oauth2ApplicationCodeUpdate) Where(ps ...predicate.Oauth2ApplicationCode) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.Where(ps...)
	return ocu
}

// SetGrantID sets the "grant_id" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetGrantID(i int64) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ResetGrantID()
	ocu.mutation.SetGrantID(i)
	return ocu
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableGrantID(i *int64) *Oauth2ApplicationCodeUpdate {
	if i != nil {
		ocu.SetGrantID(*i)
	}
	return ocu
}

// AddGrantID adds i to the "grant_id" field.
func (ocu *Oauth2ApplicationCodeUpdate) AddGrantID(i int64) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.AddGrantID(i)
	return ocu
}

// ClearGrantID clears the value of the "grant_id" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearGrantID() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearGrantID()
	return ocu
}

// SetCode sets the "code" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetCode(s string) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.SetCode(s)
	return ocu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableCode(s *string) *Oauth2ApplicationCodeUpdate {
	if s != nil {
		ocu.SetCode(*s)
	}
	return ocu
}

// ClearCode clears the value of the "code" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearCode() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearCode()
	return ocu
}

// SetCodeChallenge sets the "code_challenge" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetCodeChallenge(s string) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.SetCodeChallenge(s)
	return ocu
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableCodeChallenge(s *string) *Oauth2ApplicationCodeUpdate {
	if s != nil {
		ocu.SetCodeChallenge(*s)
	}
	return ocu
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearCodeChallenge() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearCodeChallenge()
	return ocu
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetCodeChallengeMethod(s string) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.SetCodeChallengeMethod(s)
	return ocu
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableCodeChallengeMethod(s *string) *Oauth2ApplicationCodeUpdate {
	if s != nil {
		ocu.SetCodeChallengeMethod(*s)
	}
	return ocu
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearCodeChallengeMethod() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearCodeChallengeMethod()
	return ocu
}

// SetRedirectURI sets the "redirect_uri" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetRedirectURI(s string) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.SetRedirectURI(s)
	return ocu
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableRedirectURI(s *string) *Oauth2ApplicationCodeUpdate {
	if s != nil {
		ocu.SetRedirectURI(*s)
	}
	return ocu
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearRedirectURI() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearRedirectURI()
	return ocu
}

// SetValidUntil sets the "valid_until" field.
func (ocu *Oauth2ApplicationCodeUpdate) SetValidUntil(t time.Time) *Oauth2ApplicationCodeUpdate {
	ocu.mutation.SetValidUntil(t)
	return ocu
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (ocu *Oauth2ApplicationCodeUpdate) SetNillableValidUntil(t *time.Time) *Oauth2ApplicationCodeUpdate {
	if t != nil {
		ocu.SetValidUntil(*t)
	}
	return ocu
}

// ClearValidUntil clears the value of the "valid_until" field.
func (ocu *Oauth2ApplicationCodeUpdate) ClearValidUntil() *Oauth2ApplicationCodeUpdate {
	ocu.mutation.ClearValidUntil()
	return ocu
}

// Mutation returns the Oauth2ApplicationCodeMutation object of the builder.
func (ocu *Oauth2ApplicationCodeUpdate) Mutation() *Oauth2ApplicationCodeMutation {
	return ocu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ocu *Oauth2ApplicationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ocu.sqlSave, ocu.mutation, ocu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ocu *Oauth2ApplicationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := ocu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ocu *Oauth2ApplicationCodeUpdate) Exec(ctx context.Context) error {
	_, err := ocu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocu *Oauth2ApplicationCodeUpdate) ExecX(ctx context.Context) {
	if err := ocu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ocu *Oauth2ApplicationCodeUpdate) check() error {
	if v, ok := ocu.mutation.Code(); ok {
		if err := oauth2applicationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code": %w`, err)}
		}
	}
	if v, ok := ocu.mutation.CodeChallenge(); ok {
		if err := oauth2applicationcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := ocu.mutation.CodeChallengeMethod(); ok {
		if err := oauth2applicationcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := ocu.mutation.RedirectURI(); ok {
		if err := oauth2applicationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.redirect_uri": %w`, err)}
		}
	}
	return nil
}

func (ocu *Oauth2ApplicationCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ocu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2applicationcode.Table, oauth2applicationcode.Columns, sqlgraph.NewFieldSpec(oauth2applicationcode.FieldID, field.TypeInt))
	if ps := ocu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ocu.mutation.GrantID(); ok {
		_spec.SetField(oauth2applicationcode.FieldGrantID, field.TypeInt64, value)
	}
	if value, ok := ocu.mutation.AddedGrantID(); ok {
		_spec.AddField(oauth2applicationcode.FieldGrantID, field.TypeInt64, value)
	}
	if ocu.mutation.GrantIDCleared() {
		_spec.ClearField(oauth2applicationcode.FieldGrantID, field.TypeInt64)
	}
	if value, ok := ocu.mutation.Code(); ok {
		_spec.SetField(oauth2applicationcode.FieldCode, field.TypeString, value)
	}
	if ocu.mutation.CodeCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCode, field.TypeString)
	}
	if value, ok := ocu.mutation.CodeChallenge(); ok {
		_spec.SetField(oauth2applicationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if ocu.mutation.CodeChallengeCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := ocu.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauth2applicationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if ocu.mutation.CodeChallengeMethodCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCodeChallengeMethod, field.TypeString)
	}
	if value, ok := ocu.mutation.RedirectURI(); ok {
		_spec.SetField(oauth2applicationcode.FieldRedirectURI, field.TypeString, value)
	}
	if ocu.mutation.RedirectURICleared() {
		_spec.ClearField(oauth2applicationcode.FieldRedirectURI, field.TypeString)
	}
	if value, ok := ocu.mutation.ValidUntil(); ok {
		_spec.SetField(oauth2applicationcode.FieldValidUntil, field.TypeTime, value)
	}
	if ocu.mutation.ValidUntilCleared() {
		_spec.ClearField(oauth2applicationcode.FieldValidUntil, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ocu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2applicationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ocu.mutation.done = true
	return n, nil
}

// Oauth2ApplicationCodeUpdateOne is the builder for updating a single Oauth2ApplicationCode entity.
type Oauth2ApplicationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Oauth2ApplicationCodeMutation
}

// SetGrantID sets the "grant_id" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetGrantID(i int64) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ResetGrantID()
	ocuo.mutation.SetGrantID(i)
	return ocuo
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableGrantID(i *int64) *Oauth2ApplicationCodeUpdateOne {
	if i != nil {
		ocuo.SetGrantID(*i)
	}
	return ocuo
}

// AddGrantID adds i to the "grant_id" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) AddGrantID(i int64) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.AddGrantID(i)
	return ocuo
}

// ClearGrantID clears the value of the "grant_id" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearGrantID() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearGrantID()
	return ocuo
}

// SetCode sets the "code" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetCode(s string) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.SetCode(s)
	return ocuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableCode(s *string) *Oauth2ApplicationCodeUpdateOne {
	if s != nil {
		ocuo.SetCode(*s)
	}
	return ocuo
}

// ClearCode clears the value of the "code" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearCode() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearCode()
	return ocuo
}

// SetCodeChallenge sets the "code_challenge" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetCodeChallenge(s string) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.SetCodeChallenge(s)
	return ocuo
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableCodeChallenge(s *string) *Oauth2ApplicationCodeUpdateOne {
	if s != nil {
		ocuo.SetCodeChallenge(*s)
	}
	return ocuo
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearCodeChallenge() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearCodeChallenge()
	return ocuo
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetCodeChallengeMethod(s string) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.SetCodeChallengeMethod(s)
	return ocuo
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableCodeChallengeMethod(s *string) *Oauth2ApplicationCodeUpdateOne {
	if s != nil {
		ocuo.SetCodeChallengeMethod(*s)
	}
	return ocuo
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearCodeChallengeMethod() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearCodeChallengeMethod()
	return ocuo
}

// SetRedirectURI sets the "redirect_uri" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetRedirectURI(s string) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.SetRedirectURI(s)
	return ocuo
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableRedirectURI(s *string) *Oauth2ApplicationCodeUpdateOne {
	if s != nil {
		ocuo.SetRedirectURI(*s)
	}
	return ocuo
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearRedirectURI() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearRedirectURI()
	return ocuo
}

// SetValidUntil sets the "valid_until" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetValidUntil(t time.Time) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.SetValidUntil(t)
	return ocuo
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SetNillableValidUntil(t *time.Time) *Oauth2ApplicationCodeUpdateOne {
	if t != nil {
		ocuo.SetValidUntil(*t)
	}
	return ocuo
}

// ClearValidUntil clears the value of the "valid_until" field.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ClearValidUntil() *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.ClearValidUntil()
	return ocuo
}

// Mutation returns the Oauth2ApplicationCodeMutation object of the builder.
func (ocuo *Oauth2ApplicationCodeUpdateOne) Mutation() *Oauth2ApplicationCodeMutation {
	return ocuo.mutation
}

// Where appends a list predicates to the Oauth2ApplicationCodeUpdate builder.
func (ocuo *Oauth2ApplicationCodeUpdateOne) Where(ps ...predicate.Oauth2ApplicationCode) *Oauth2ApplicationCodeUpdateOne {
	ocuo.mutation.Where(ps...)
	return ocuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ocuo *Oauth2ApplicationCodeUpdateOne) Select(field string, fields ...string) *Oauth2ApplicationCodeUpdateOne {
	ocuo.fields = append([]string{field}, fields...)
	return ocuo
}

// Save executes the query and returns the updated Oauth2ApplicationCode entity.
func (ocuo *Oauth2ApplicationCodeUpdateOne) Save(ctx context.Context) (*Oauth2ApplicationCode, error) {
	return withHooks(ctx, ocuo.sqlSave, ocuo.mutation, ocuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ocuo *Oauth2ApplicationCodeUpdateOne) SaveX(ctx context.Context) *Oauth2ApplicationCode {
	node, err := ocuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ocuo *Oauth2ApplicationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := ocuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocuo *Oauth2ApplicationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := ocuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ocuo *Oauth2ApplicationCodeUpdateOne) check() error {
	if v, ok := ocuo.mutation.Code(); ok {
		if err := oauth2applicationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code": %w`, err)}
		}
	}
	if v, ok := ocuo.mutation.CodeChallenge(); ok {
		if err := oauth2applicationcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := ocuo.mutation.CodeChallengeMethod(); ok {
		if err := oauth2applicationcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := ocuo.mutation.RedirectURI(); ok {
		if err := oauth2applicationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`models: validator failed for field "Oauth2ApplicationCode.redirect_uri": %w`, err)}
		}
	}
	return nil
}

func (ocuo *Oauth2ApplicationCodeUpdateOne) sqlSave(ctx context.Context) (_node *Oauth2ApplicationCode, err error) {
	if err := ocuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2applicationcode.Table, oauth2applicationcode.Columns, sqlgraph.NewFieldSpec(oauth2applicationcode.FieldID, field.TypeInt))
	id, ok := ocuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "Oauth2ApplicationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ocuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauth2applicationcode.FieldID)
		for _, f := range fields {
			if !oauth2applicationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != oauth2applicationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ocuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ocuo.mutation.GrantID(); ok {
		_spec.SetField(oauth2applicationcode.FieldGrantID, field.TypeInt64, value)
	}
	if value, ok := ocuo.mutation.AddedGrantID(); ok {
		_spec.AddField(oauth2applicationcode.FieldGrantID, field.TypeInt64, value)
	}
	if ocuo.mutation.GrantIDCleared() {
		_spec.ClearField(oauth2applicationcode.FieldGrantID, field.TypeInt64)
	}
	if value, ok := ocuo.mutation.Code(); ok {
		_spec.SetField(oauth2applicationcode.FieldCode, field.TypeString, value)
	}
	if ocuo.mutation.CodeCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCode, field.TypeString)
	}
	if value, ok := ocuo.mutation.CodeChallenge(); ok {
		_spec.SetField(oauth2applicationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if ocuo.mutation.CodeChallengeCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := ocuo.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauth2applicationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if ocuo.mutation.CodeChallengeMethodCleared() {
		_spec.ClearField(oauth2applicationcode.FieldCodeChallengeMethod, field.TypeString)
	}
	if value, ok := ocuo.mutation.RedirectURI(); ok {
		_spec.SetField(oauth2applicationcode.FieldRedirectURI, field.TypeString, value)
	}
	if ocuo.mutation.RedirectURICleared() {
		_spec.ClearField(oauth2applicationcode.FieldRedirectURI, field.TypeString)
	}
	if value, ok := ocuo.mutation.ValidUntil(); ok {
		_spec.SetField(oauth2applicationcode.FieldValidUntil, field.TypeTime, value)
	}
	if ocuo.mutation.ValidUntilCleared() {
		_spec.ClearField(oauth2applicationcode.FieldValidUntil, field.TypeTime)
	}
	_node = &Oauth2ApplicationCode{config: ocuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ocuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2applicationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ocuo.mutation.done = true
	return _node, nil
}
