// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/gitbundle/store/models/protectedbranch"
)

// ProtectedBranch is the model entity for the ProtectedBranch schema.
type ProtectedBranch struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID int64 `json:"repo_id,omitempty"`
	// BranchName holds the value of the "branch_name" field.
	BranchName string `json:"branch_name,omitempty"`
	// CanPush holds the value of the "can_push" field.
	CanPush bool `json:"can_push,omitempty"`
	// EnableWhitelist holds the value of the "enable_whitelist" field.
	EnableWhitelist bool `json:"enable_whitelist,omitempty"`
	// WhitelistUserIDs holds the value of the "whitelist_user_i_ds" field.
	WhitelistUserIDs string `json:"whitelist_user_i_ds,omitempty"`
	// WhitelistTeamIDs holds the value of the "whitelist_team_i_ds" field.
	WhitelistTeamIDs string `json:"whitelist_team_i_ds,omitempty"`
	// EnableMergeWhitelist holds the value of the "enable_merge_whitelist" field.
	EnableMergeWhitelist bool `json:"enable_merge_whitelist,omitempty"`
	// WhitelistDeployKeys holds the value of the "whitelist_deploy_keys" field.
	WhitelistDeployKeys bool `json:"whitelist_deploy_keys,omitempty"`
	// MergeWhitelistUserIDs holds the value of the "merge_whitelist_user_i_ds" field.
	MergeWhitelistUserIDs string `json:"merge_whitelist_user_i_ds,omitempty"`
	// MergeWhitelistTeamIDs holds the value of the "merge_whitelist_team_i_ds" field.
	MergeWhitelistTeamIDs string `json:"merge_whitelist_team_i_ds,omitempty"`
	// EnableStatusCheck holds the value of the "enable_status_check" field.
	EnableStatusCheck bool `json:"enable_status_check,omitempty"`
	// StatusCheckContexts holds the value of the "status_check_contexts" field.
	StatusCheckContexts string `json:"status_check_contexts,omitempty"`
	// EnableApprovalsWhitelist holds the value of the "enable_approvals_whitelist" field.
	EnableApprovalsWhitelist bool `json:"enable_approvals_whitelist,omitempty"`
	// ApprovalsWhitelistUserIDs holds the value of the "approvals_whitelist_user_i_ds" field.
	ApprovalsWhitelistUserIDs string `json:"approvals_whitelist_user_i_ds,omitempty"`
	// ApprovalsWhitelistTeamIDs holds the value of the "approvals_whitelist_team_i_ds" field.
	ApprovalsWhitelistTeamIDs string `json:"approvals_whitelist_team_i_ds,omitempty"`
	// RequiredApprovals holds the value of the "required_approvals" field.
	RequiredApprovals int64 `json:"required_approvals,omitempty"`
	// BlockOnRejectedReviews holds the value of the "block_on_rejected_reviews" field.
	BlockOnRejectedReviews bool `json:"block_on_rejected_reviews,omitempty"`
	// BlockOnOfficialReviewRequests holds the value of the "block_on_official_review_requests" field.
	BlockOnOfficialReviewRequests bool `json:"block_on_official_review_requests,omitempty"`
	// BlockOnOutdatedBranch holds the value of the "block_on_outdated_branch" field.
	BlockOnOutdatedBranch bool `json:"block_on_outdated_branch,omitempty"`
	// DismissStaleApprovals holds the value of the "dismiss_stale_approvals" field.
	DismissStaleApprovals bool `json:"dismiss_stale_approvals,omitempty"`
	// RequireSignedCommits holds the value of the "require_signed_commits" field.
	RequireSignedCommits bool `json:"require_signed_commits,omitempty"`
	// ProtectedFilePatterns holds the value of the "protected_file_patterns" field.
	ProtectedFilePatterns string `json:"protected_file_patterns,omitempty"`
	// UnprotectedFilePatterns holds the value of the "unprotected_file_patterns" field.
	UnprotectedFilePatterns string `json:"unprotected_file_patterns,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProtectedBranch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case protectedbranch.FieldCanPush, protectedbranch.FieldEnableWhitelist, protectedbranch.FieldEnableMergeWhitelist, protectedbranch.FieldWhitelistDeployKeys, protectedbranch.FieldEnableStatusCheck, protectedbranch.FieldEnableApprovalsWhitelist, protectedbranch.FieldBlockOnRejectedReviews, protectedbranch.FieldBlockOnOfficialReviewRequests, protectedbranch.FieldBlockOnOutdatedBranch, protectedbranch.FieldDismissStaleApprovals, protectedbranch.FieldRequireSignedCommits:
			values[i] = new(sql.NullBool)
		case protectedbranch.FieldID, protectedbranch.FieldRepoID, protectedbranch.FieldRequiredApprovals:
			values[i] = new(sql.NullInt64)
		case protectedbranch.FieldBranchName, protectedbranch.FieldWhitelistUserIDs, protectedbranch.FieldWhitelistTeamIDs, protectedbranch.FieldMergeWhitelistUserIDs, protectedbranch.FieldMergeWhitelistTeamIDs, protectedbranch.FieldStatusCheckContexts, protectedbranch.FieldApprovalsWhitelistUserIDs, protectedbranch.FieldApprovalsWhitelistTeamIDs, protectedbranch.FieldProtectedFilePatterns, protectedbranch.FieldUnprotectedFilePatterns:
			values[i] = new(sql.NullString)
		case protectedbranch.FieldCreatedAt, protectedbranch.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProtectedBranch fields.
func (pb *ProtectedBranch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case protectedbranch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pb.ID = int(value.Int64)
		case protectedbranch.FieldRepoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				pb.RepoID = value.Int64
			}
		case protectedbranch.FieldBranchName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch_name", values[i])
			} else if value.Valid {
				pb.BranchName = value.String
			}
		case protectedbranch.FieldCanPush:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_push", values[i])
			} else if value.Valid {
				pb.CanPush = value.Bool
			}
		case protectedbranch.FieldEnableWhitelist:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_whitelist", values[i])
			} else if value.Valid {
				pb.EnableWhitelist = value.Bool
			}
		case protectedbranch.FieldWhitelistUserIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field whitelist_user_i_ds", values[i])
			} else if value.Valid {
				pb.WhitelistUserIDs = value.String
			}
		case protectedbranch.FieldWhitelistTeamIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field whitelist_team_i_ds", values[i])
			} else if value.Valid {
				pb.WhitelistTeamIDs = value.String
			}
		case protectedbranch.FieldEnableMergeWhitelist:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_merge_whitelist", values[i])
			} else if value.Valid {
				pb.EnableMergeWhitelist = value.Bool
			}
		case protectedbranch.FieldWhitelistDeployKeys:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field whitelist_deploy_keys", values[i])
			} else if value.Valid {
				pb.WhitelistDeployKeys = value.Bool
			}
		case protectedbranch.FieldMergeWhitelistUserIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field merge_whitelist_user_i_ds", values[i])
			} else if value.Valid {
				pb.MergeWhitelistUserIDs = value.String
			}
		case protectedbranch.FieldMergeWhitelistTeamIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field merge_whitelist_team_i_ds", values[i])
			} else if value.Valid {
				pb.MergeWhitelistTeamIDs = value.String
			}
		case protectedbranch.FieldEnableStatusCheck:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_status_check", values[i])
			} else if value.Valid {
				pb.EnableStatusCheck = value.Bool
			}
		case protectedbranch.FieldStatusCheckContexts:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_check_contexts", values[i])
			} else if value.Valid {
				pb.StatusCheckContexts = value.String
			}
		case protectedbranch.FieldEnableApprovalsWhitelist:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_approvals_whitelist", values[i])
			} else if value.Valid {
				pb.EnableApprovalsWhitelist = value.Bool
			}
		case protectedbranch.FieldApprovalsWhitelistUserIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approvals_whitelist_user_i_ds", values[i])
			} else if value.Valid {
				pb.ApprovalsWhitelistUserIDs = value.String
			}
		case protectedbranch.FieldApprovalsWhitelistTeamIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approvals_whitelist_team_i_ds", values[i])
			} else if value.Valid {
				pb.ApprovalsWhitelistTeamIDs = value.String
			}
		case protectedbranch.FieldRequiredApprovals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field required_approvals", values[i])
			} else if value.Valid {
				pb.RequiredApprovals = value.Int64
			}
		case protectedbranch.FieldBlockOnRejectedReviews:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field block_on_rejected_reviews", values[i])
			} else if value.Valid {
				pb.BlockOnRejectedReviews = value.Bool
			}
		case protectedbranch.FieldBlockOnOfficialReviewRequests:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field block_on_official_review_requests", values[i])
			} else if value.Valid {
				pb.BlockOnOfficialReviewRequests = value.Bool
			}
		case protectedbranch.FieldBlockOnOutdatedBranch:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field block_on_outdated_branch", values[i])
			} else if value.Valid {
				pb.BlockOnOutdatedBranch = value.Bool
			}
		case protectedbranch.FieldDismissStaleApprovals:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field dismiss_stale_approvals", values[i])
			} else if value.Valid {
				pb.DismissStaleApprovals = value.Bool
			}
		case protectedbranch.FieldRequireSignedCommits:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_signed_commits", values[i])
			} else if value.Valid {
				pb.RequireSignedCommits = value.Bool
			}
		case protectedbranch.FieldProtectedFilePatterns:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protected_file_patterns", values[i])
			} else if value.Valid {
				pb.ProtectedFilePatterns = value.String
			}
		case protectedbranch.FieldUnprotectedFilePatterns:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unprotected_file_patterns", values[i])
			} else if value.Valid {
				pb.UnprotectedFilePatterns = value.String
			}
		case protectedbranch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pb.CreatedAt = value.Time
			}
		case protectedbranch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pb.UpdatedAt = value.Time
			}
		default:
			pb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProtectedBranch.
// This includes values selected through modifiers, order, etc.
func (pb *ProtectedBranch) Value(name string) (ent.Value, error) {
	return pb.selectValues.Get(name)
}

// Update returns a builder for updating this ProtectedBranch.
// Note that you need to call ProtectedBranch.Unwrap() before calling this method if this ProtectedBranch
// was returned from a transaction, and the transaction was committed or rolled back.
func (pb *ProtectedBranch) Update() *ProtectedBranchUpdateOne {
	return NewProtectedBranchClient(pb.config).UpdateOne(pb)
}

// Unwrap unwraps the ProtectedBranch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pb *ProtectedBranch) Unwrap() *ProtectedBranch {
	_tx, ok := pb.config.driver.(*txDriver)
	if !ok {
		panic("models: ProtectedBranch is not a transactional entity")
	}
	pb.config.driver = _tx.drv
	return pb
}

// String implements the fmt.Stringer.
func (pb *ProtectedBranch) String() string {
	var builder strings.Builder
	builder.WriteString("ProtectedBranch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pb.ID))
	builder.WriteString("repo_id=")
	builder.WriteString(fmt.Sprintf("%v", pb.RepoID))
	builder.WriteString(", ")
	builder.WriteString("branch_name=")
	builder.WriteString(pb.BranchName)
	builder.WriteString(", ")
	builder.WriteString("can_push=")
	builder.WriteString(fmt.Sprintf("%v", pb.CanPush))
	builder.WriteString(", ")
	builder.WriteString("enable_whitelist=")
	builder.WriteString(fmt.Sprintf("%v", pb.EnableWhitelist))
	builder.WriteString(", ")
	builder.WriteString("whitelist_user_i_ds=")
	builder.WriteString(pb.WhitelistUserIDs)
	builder.WriteString(", ")
	builder.WriteString("whitelist_team_i_ds=")
	builder.WriteString(pb.WhitelistTeamIDs)
	builder.WriteString(", ")
	builder.WriteString("enable_merge_whitelist=")
	builder.WriteString(fmt.Sprintf("%v", pb.EnableMergeWhitelist))
	builder.WriteString(", ")
	builder.WriteString("whitelist_deploy_keys=")
	builder.WriteString(fmt.Sprintf("%v", pb.WhitelistDeployKeys))
	builder.WriteString(", ")
	builder.WriteString("merge_whitelist_user_i_ds=")
	builder.WriteString(pb.MergeWhitelistUserIDs)
	builder.WriteString(", ")
	builder.WriteString("merge_whitelist_team_i_ds=")
	builder.WriteString(pb.MergeWhitelistTeamIDs)
	builder.WriteString(", ")
	builder.WriteString("enable_status_check=")
	builder.WriteString(fmt.Sprintf("%v", pb.EnableStatusCheck))
	builder.WriteString(", ")
	builder.WriteString("status_check_contexts=")
	builder.WriteString(pb.StatusCheckContexts)
	builder.WriteString(", ")
	builder.WriteString("enable_approvals_whitelist=")
	builder.WriteString(fmt.Sprintf("%v", pb.EnableApprovalsWhitelist))
	builder.WriteString(", ")
	builder.WriteString("approvals_whitelist_user_i_ds=")
	builder.WriteString(pb.ApprovalsWhitelistUserIDs)
	builder.WriteString(", ")
	builder.WriteString("approvals_whitelist_team_i_ds=")
	builder.WriteString(pb.ApprovalsWhitelistTeamIDs)
	builder.WriteString(", ")
	builder.WriteString("required_approvals=")
	builder.WriteString(fmt.Sprintf("%v", pb.RequiredApprovals))
	builder.WriteString(", ")
	builder.WriteString("block_on_rejected_reviews=")
	builder.WriteString(fmt.Sprintf("%v", pb.BlockOnRejectedReviews))
	builder.WriteString(", ")
	builder.WriteString("block_on_official_review_requests=")
	builder.WriteString(fmt.Sprintf("%v", pb.BlockOnOfficialReviewRequests))
	builder.WriteString(", ")
	builder.WriteString("block_on_outdated_branch=")
	builder.WriteString(fmt.Sprintf("%v", pb.BlockOnOutdatedBranch))
	builder.WriteString(", ")
	builder.WriteString("dismiss_stale_approvals=")
	builder.WriteString(fmt.Sprintf("%v", pb.DismissStaleApprovals))
	builder.WriteString(", ")
	builder.WriteString("require_signed_commits=")
	builder.WriteString(fmt.Sprintf("%v", pb.RequireSignedCommits))
	builder.WriteString(", ")
	builder.WriteString("protected_file_patterns=")
	builder.WriteString(pb.ProtectedFilePatterns)
	builder.WriteString(", ")
	builder.WriteString("unprotected_file_patterns=")
	builder.WriteString(pb.UnprotectedFilePatterns)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pb.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pb.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProtectedBranches is a parsable slice of ProtectedBranch.
type ProtectedBranches []*ProtectedBranch
