// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/store/models/publickey"
)

// PublicKeyCreate is the builder for creating a PublicKey entity.
type PublicKeyCreate struct {
	config
	mutation *PublicKeyMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (pkc *PublicKeyCreate) SetOwnerID(i int64) *PublicKeyCreate {
	pkc.mutation.SetOwnerID(i)
	return pkc
}

// SetName sets the "name" field.
func (pkc *PublicKeyCreate) SetName(s string) *PublicKeyCreate {
	pkc.mutation.SetName(s)
	return pkc
}

// SetFingerprint sets the "fingerprint" field.
func (pkc *PublicKeyCreate) SetFingerprint(s string) *PublicKeyCreate {
	pkc.mutation.SetFingerprint(s)
	return pkc
}

// SetContent sets the "content" field.
func (pkc *PublicKeyCreate) SetContent(s string) *PublicKeyCreate {
	pkc.mutation.SetContent(s)
	return pkc
}

// SetMode sets the "mode" field.
func (pkc *PublicKeyCreate) SetMode(i int) *PublicKeyCreate {
	pkc.mutation.SetMode(i)
	return pkc
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableMode(i *int) *PublicKeyCreate {
	if i != nil {
		pkc.SetMode(*i)
	}
	return pkc
}

// SetType sets the "type" field.
func (pkc *PublicKeyCreate) SetType(i int) *PublicKeyCreate {
	pkc.mutation.SetType(i)
	return pkc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableType(i *int) *PublicKeyCreate {
	if i != nil {
		pkc.SetType(*i)
	}
	return pkc
}

// SetLoginSourceID sets the "login_source_id" field.
func (pkc *PublicKeyCreate) SetLoginSourceID(i int) *PublicKeyCreate {
	pkc.mutation.SetLoginSourceID(i)
	return pkc
}

// SetNillableLoginSourceID sets the "login_source_id" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableLoginSourceID(i *int) *PublicKeyCreate {
	if i != nil {
		pkc.SetLoginSourceID(*i)
	}
	return pkc
}

// SetCreatedAt sets the "created_at" field.
func (pkc *PublicKeyCreate) SetCreatedAt(t time.Time) *PublicKeyCreate {
	pkc.mutation.SetCreatedAt(t)
	return pkc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableCreatedAt(t *time.Time) *PublicKeyCreate {
	if t != nil {
		pkc.SetCreatedAt(*t)
	}
	return pkc
}

// SetUpdatedAt sets the "updated_at" field.
func (pkc *PublicKeyCreate) SetUpdatedAt(t time.Time) *PublicKeyCreate {
	pkc.mutation.SetUpdatedAt(t)
	return pkc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableUpdatedAt(t *time.Time) *PublicKeyCreate {
	if t != nil {
		pkc.SetUpdatedAt(*t)
	}
	return pkc
}

// SetVerified sets the "verified" field.
func (pkc *PublicKeyCreate) SetVerified(b bool) *PublicKeyCreate {
	pkc.mutation.SetVerified(b)
	return pkc
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (pkc *PublicKeyCreate) SetNillableVerified(b *bool) *PublicKeyCreate {
	if b != nil {
		pkc.SetVerified(*b)
	}
	return pkc
}

// Mutation returns the PublicKeyMutation object of the builder.
func (pkc *PublicKeyCreate) Mutation() *PublicKeyMutation {
	return pkc.mutation
}

// Save creates the PublicKey in the database.
func (pkc *PublicKeyCreate) Save(ctx context.Context) (*PublicKey, error) {
	pkc.defaults()
	return withHooks(ctx, pkc.sqlSave, pkc.mutation, pkc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pkc *PublicKeyCreate) SaveX(ctx context.Context) *PublicKey {
	v, err := pkc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pkc *PublicKeyCreate) Exec(ctx context.Context) error {
	_, err := pkc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkc *PublicKeyCreate) ExecX(ctx context.Context) {
	if err := pkc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pkc *PublicKeyCreate) defaults() {
	if _, ok := pkc.mutation.Mode(); !ok {
		v := publickey.DefaultMode
		pkc.mutation.SetMode(v)
	}
	if _, ok := pkc.mutation.GetType(); !ok {
		v := publickey.DefaultType
		pkc.mutation.SetType(v)
	}
	if _, ok := pkc.mutation.LoginSourceID(); !ok {
		v := publickey.DefaultLoginSourceID
		pkc.mutation.SetLoginSourceID(v)
	}
	if _, ok := pkc.mutation.CreatedAt(); !ok {
		v := publickey.DefaultCreatedAt()
		pkc.mutation.SetCreatedAt(v)
	}
	if _, ok := pkc.mutation.Verified(); !ok {
		v := publickey.DefaultVerified
		pkc.mutation.SetVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pkc *PublicKeyCreate) check() error {
	if _, ok := pkc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`models: missing required field "PublicKey.owner_id"`)}
	}
	if _, ok := pkc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`models: missing required field "PublicKey.name"`)}
	}
	if v, ok := pkc.mutation.Name(); ok {
		if err := publickey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`models: validator failed for field "PublicKey.name": %w`, err)}
		}
	}
	if _, ok := pkc.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`models: missing required field "PublicKey.fingerprint"`)}
	}
	if v, ok := pkc.mutation.Fingerprint(); ok {
		if err := publickey.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`models: validator failed for field "PublicKey.fingerprint": %w`, err)}
		}
	}
	if _, ok := pkc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`models: missing required field "PublicKey.content"`)}
	}
	if _, ok := pkc.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`models: missing required field "PublicKey.mode"`)}
	}
	if _, ok := pkc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`models: missing required field "PublicKey.type"`)}
	}
	if _, ok := pkc.mutation.LoginSourceID(); !ok {
		return &ValidationError{Name: "login_source_id", err: errors.New(`models: missing required field "PublicKey.login_source_id"`)}
	}
	if _, ok := pkc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`models: missing required field "PublicKey.created_at"`)}
	}
	if _, ok := pkc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`models: missing required field "PublicKey.verified"`)}
	}
	return nil
}

func (pkc *PublicKeyCreate) sqlSave(ctx context.Context) (*PublicKey, error) {
	if err := pkc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pkc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pkc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pkc.mutation.id = &_node.ID
	pkc.mutation.done = true
	return _node, nil
}

func (pkc *PublicKeyCreate) createSpec() (*PublicKey, *sqlgraph.CreateSpec) {
	var (
		_node = &PublicKey{config: pkc.config}
		_spec = sqlgraph.NewCreateSpec(publickey.Table, sqlgraph.NewFieldSpec(publickey.FieldID, field.TypeInt))
	)
	if value, ok := pkc.mutation.OwnerID(); ok {
		_spec.SetField(publickey.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := pkc.mutation.Name(); ok {
		_spec.SetField(publickey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pkc.mutation.Fingerprint(); ok {
		_spec.SetField(publickey.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := pkc.mutation.Content(); ok {
		_spec.SetField(publickey.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := pkc.mutation.Mode(); ok {
		_spec.SetField(publickey.FieldMode, field.TypeInt, value)
		_node.Mode = value
	}
	if value, ok := pkc.mutation.GetType(); ok {
		_spec.SetField(publickey.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := pkc.mutation.LoginSourceID(); ok {
		_spec.SetField(publickey.FieldLoginSourceID, field.TypeInt, value)
		_node.LoginSourceID = value
	}
	if value, ok := pkc.mutation.CreatedAt(); ok {
		_spec.SetField(publickey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pkc.mutation.UpdatedAt(); ok {
		_spec.SetField(publickey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pkc.mutation.Verified(); ok {
		_spec.SetField(publickey.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	return _node, _spec
}

// PublicKeyCreateBulk is the builder for creating many PublicKey entities in bulk.
type PublicKeyCreateBulk struct {
	config
	err      error
	builders []*PublicKeyCreate
}

// Save creates the PublicKey entities in the database.
func (pkcb *PublicKeyCreateBulk) Save(ctx context.Context) ([]*PublicKey, error) {
	if pkcb.err != nil {
		return nil, pkcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pkcb.builders))
	nodes := make([]*PublicKey, len(pkcb.builders))
	mutators := make([]Mutator, len(pkcb.builders))
	for i := range pkcb.builders {
		func(i int, root context.Context) {
			builder := pkcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PublicKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pkcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pkcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pkcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pkcb *PublicKeyCreateBulk) SaveX(ctx context.Context) []*PublicKey {
	v, err := pkcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pkcb *PublicKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := pkcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkcb *PublicKeyCreateBulk) ExecX(ctx context.Context) {
	if err := pkcb.Exec(ctx); err != nil {
		panic(err)
	}
}
