// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/store/models/teamunit"
)

// TeamUnit is the model entity for the TeamUnit schema.
type TeamUnit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID int64 `json:"org_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// Type holds the value of the "type" field.
	Type int `json:"type,omitempty"`
	// AccessMode holds the value of the "access_mode" field.
	AccessMode   int `json:"access_mode,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamUnit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamunit.FieldID, teamunit.FieldOrgID, teamunit.FieldTeamID, teamunit.FieldType, teamunit.FieldAccessMode:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamUnit fields.
func (tu *TeamUnit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamunit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tu.ID = int(value.Int64)
		case teamunit.FieldOrgID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				tu.OrgID = value.Int64
			}
		case teamunit.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				tu.TeamID = value.Int64
			}
		case teamunit.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				tu.Type = int(value.Int64)
			}
		case teamunit.FieldAccessMode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field access_mode", values[i])
			} else if value.Valid {
				tu.AccessMode = int(value.Int64)
			}
		default:
			tu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamUnit.
// This includes values selected through modifiers, order, etc.
func (tu *TeamUnit) Value(name string) (ent.Value, error) {
	return tu.selectValues.Get(name)
}

// Update returns a builder for updating this TeamUnit.
// Note that you need to call TeamUnit.Unwrap() before calling this method if this TeamUnit
// was returned from a transaction, and the transaction was committed or rolled back.
func (tu *TeamUnit) Update() *TeamUnitUpdateOne {
	return NewTeamUnitClient(tu.config).UpdateOne(tu)
}

// Unwrap unwraps the TeamUnit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tu *TeamUnit) Unwrap() *TeamUnit {
	_tx, ok := tu.config.driver.(*txDriver)
	if !ok {
		panic("models: TeamUnit is not a transactional entity")
	}
	tu.config.driver = _tx.drv
	return tu
}

// String implements the fmt.Stringer.
func (tu *TeamUnit) String() string {
	var builder strings.Builder
	builder.WriteString("TeamUnit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tu.ID))
	builder.WriteString("org_id=")
	builder.WriteString(fmt.Sprintf("%v", tu.OrgID))
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", tu.TeamID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", tu.Type))
	builder.WriteString(", ")
	builder.WriteString("access_mode=")
	builder.WriteString(fmt.Sprintf("%v", tu.AccessMode))
	builder.WriteByte(')')
	return builder.String()
}

// TeamUnits is a parsable slice of TeamUnit.
type TeamUnits []*TeamUnit
