// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/store/models/predicate"
	"github.com/gitbundle/server/store/models/watch"
)

// WatchUpdate is the builder for updating Watch entities.
type WatchUpdate struct {
	config
	hooks    []Hook
	mutation *WatchMutation
}

// Where appends a list predicates to the WatchUpdate builder.
func (wu *WatchUpdate) Where(ps ...predicate.Watch) *WatchUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WatchUpdate) SetUserID(i int64) *WatchUpdate {
	wu.mutation.ResetUserID()
	wu.mutation.SetUserID(i)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WatchUpdate) SetNillableUserID(i *int64) *WatchUpdate {
	if i != nil {
		wu.SetUserID(*i)
	}
	return wu
}

// AddUserID adds i to the "user_id" field.
func (wu *WatchUpdate) AddUserID(i int64) *WatchUpdate {
	wu.mutation.AddUserID(i)
	return wu
}

// ClearUserID clears the value of the "user_id" field.
func (wu *WatchUpdate) ClearUserID() *WatchUpdate {
	wu.mutation.ClearUserID()
	return wu
}

// SetRepoID sets the "repo_id" field.
func (wu *WatchUpdate) SetRepoID(i int64) *WatchUpdate {
	wu.mutation.ResetRepoID()
	wu.mutation.SetRepoID(i)
	return wu
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (wu *WatchUpdate) SetNillableRepoID(i *int64) *WatchUpdate {
	if i != nil {
		wu.SetRepoID(*i)
	}
	return wu
}

// AddRepoID adds i to the "repo_id" field.
func (wu *WatchUpdate) AddRepoID(i int64) *WatchUpdate {
	wu.mutation.AddRepoID(i)
	return wu
}

// ClearRepoID clears the value of the "repo_id" field.
func (wu *WatchUpdate) ClearRepoID() *WatchUpdate {
	wu.mutation.ClearRepoID()
	return wu
}

// SetMode sets the "mode" field.
func (wu *WatchUpdate) SetMode(i int16) *WatchUpdate {
	wu.mutation.ResetMode()
	wu.mutation.SetMode(i)
	return wu
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (wu *WatchUpdate) SetNillableMode(i *int16) *WatchUpdate {
	if i != nil {
		wu.SetMode(*i)
	}
	return wu
}

// AddMode adds i to the "mode" field.
func (wu *WatchUpdate) AddMode(i int16) *WatchUpdate {
	wu.mutation.AddMode(i)
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WatchUpdate) SetCreatedAt(t time.Time) *WatchUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WatchUpdate) SetNillableCreatedAt(t *time.Time) *WatchUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WatchUpdate) SetUpdatedAt(t time.Time) *WatchUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wu *WatchUpdate) SetNillableUpdatedAt(t *time.Time) *WatchUpdate {
	if t != nil {
		wu.SetUpdatedAt(*t)
	}
	return wu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (wu *WatchUpdate) ClearUpdatedAt() *WatchUpdate {
	wu.mutation.ClearUpdatedAt()
	return wu
}

// Mutation returns the WatchMutation object of the builder.
func (wu *WatchUpdate) Mutation() *WatchMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WatchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WatchUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WatchUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WatchUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WatchUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(watch.Table, watch.Columns, sqlgraph.NewFieldSpec(watch.FieldID, field.TypeInt))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.UserID(); ok {
		_spec.SetField(watch.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedUserID(); ok {
		_spec.AddField(watch.FieldUserID, field.TypeInt64, value)
	}
	if wu.mutation.UserIDCleared() {
		_spec.ClearField(watch.FieldUserID, field.TypeInt64)
	}
	if value, ok := wu.mutation.RepoID(); ok {
		_spec.SetField(watch.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedRepoID(); ok {
		_spec.AddField(watch.FieldRepoID, field.TypeInt64, value)
	}
	if wu.mutation.RepoIDCleared() {
		_spec.ClearField(watch.FieldRepoID, field.TypeInt64)
	}
	if value, ok := wu.mutation.Mode(); ok {
		_spec.SetField(watch.FieldMode, field.TypeInt16, value)
	}
	if value, ok := wu.mutation.AddedMode(); ok {
		_spec.AddField(watch.FieldMode, field.TypeInt16, value)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(watch.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(watch.FieldUpdatedAt, field.TypeTime, value)
	}
	if wu.mutation.UpdatedAtCleared() {
		_spec.ClearField(watch.FieldUpdatedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{watch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WatchUpdateOne is the builder for updating a single Watch entity.
type WatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WatchMutation
}

// SetUserID sets the "user_id" field.
func (wuo *WatchUpdateOne) SetUserID(i int64) *WatchUpdateOne {
	wuo.mutation.ResetUserID()
	wuo.mutation.SetUserID(i)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WatchUpdateOne) SetNillableUserID(i *int64) *WatchUpdateOne {
	if i != nil {
		wuo.SetUserID(*i)
	}
	return wuo
}

// AddUserID adds i to the "user_id" field.
func (wuo *WatchUpdateOne) AddUserID(i int64) *WatchUpdateOne {
	wuo.mutation.AddUserID(i)
	return wuo
}

// ClearUserID clears the value of the "user_id" field.
func (wuo *WatchUpdateOne) ClearUserID() *WatchUpdateOne {
	wuo.mutation.ClearUserID()
	return wuo
}

// SetRepoID sets the "repo_id" field.
func (wuo *WatchUpdateOne) SetRepoID(i int64) *WatchUpdateOne {
	wuo.mutation.ResetRepoID()
	wuo.mutation.SetRepoID(i)
	return wuo
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (wuo *WatchUpdateOne) SetNillableRepoID(i *int64) *WatchUpdateOne {
	if i != nil {
		wuo.SetRepoID(*i)
	}
	return wuo
}

// AddRepoID adds i to the "repo_id" field.
func (wuo *WatchUpdateOne) AddRepoID(i int64) *WatchUpdateOne {
	wuo.mutation.AddRepoID(i)
	return wuo
}

// ClearRepoID clears the value of the "repo_id" field.
func (wuo *WatchUpdateOne) ClearRepoID() *WatchUpdateOne {
	wuo.mutation.ClearRepoID()
	return wuo
}

// SetMode sets the "mode" field.
func (wuo *WatchUpdateOne) SetMode(i int16) *WatchUpdateOne {
	wuo.mutation.ResetMode()
	wuo.mutation.SetMode(i)
	return wuo
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (wuo *WatchUpdateOne) SetNillableMode(i *int16) *WatchUpdateOne {
	if i != nil {
		wuo.SetMode(*i)
	}
	return wuo
}

// AddMode adds i to the "mode" field.
func (wuo *WatchUpdateOne) AddMode(i int16) *WatchUpdateOne {
	wuo.mutation.AddMode(i)
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WatchUpdateOne) SetCreatedAt(t time.Time) *WatchUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WatchUpdateOne) SetNillableCreatedAt(t *time.Time) *WatchUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WatchUpdateOne) SetUpdatedAt(t time.Time) *WatchUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wuo *WatchUpdateOne) SetNillableUpdatedAt(t *time.Time) *WatchUpdateOne {
	if t != nil {
		wuo.SetUpdatedAt(*t)
	}
	return wuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (wuo *WatchUpdateOne) ClearUpdatedAt() *WatchUpdateOne {
	wuo.mutation.ClearUpdatedAt()
	return wuo
}

// Mutation returns the WatchMutation object of the builder.
func (wuo *WatchUpdateOne) Mutation() *WatchMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WatchUpdate builder.
func (wuo *WatchUpdateOne) Where(ps ...predicate.Watch) *WatchUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WatchUpdateOne) Select(field string, fields ...string) *WatchUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Watch entity.
func (wuo *WatchUpdateOne) Save(ctx context.Context) (*Watch, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WatchUpdateOne) SaveX(ctx context.Context) *Watch {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WatchUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WatchUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WatchUpdateOne) sqlSave(ctx context.Context) (_node *Watch, err error) {
	_spec := sqlgraph.NewUpdateSpec(watch.Table, watch.Columns, sqlgraph.NewFieldSpec(watch.FieldID, field.TypeInt))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "Watch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, watch.FieldID)
		for _, f := range fields {
			if !watch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != watch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.UserID(); ok {
		_spec.SetField(watch.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedUserID(); ok {
		_spec.AddField(watch.FieldUserID, field.TypeInt64, value)
	}
	if wuo.mutation.UserIDCleared() {
		_spec.ClearField(watch.FieldUserID, field.TypeInt64)
	}
	if value, ok := wuo.mutation.RepoID(); ok {
		_spec.SetField(watch.FieldRepoID, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedRepoID(); ok {
		_spec.AddField(watch.FieldRepoID, field.TypeInt64, value)
	}
	if wuo.mutation.RepoIDCleared() {
		_spec.ClearField(watch.FieldRepoID, field.TypeInt64)
	}
	if value, ok := wuo.mutation.Mode(); ok {
		_spec.SetField(watch.FieldMode, field.TypeInt16, value)
	}
	if value, ok := wuo.mutation.AddedMode(); ok {
		_spec.AddField(watch.FieldMode, field.TypeInt16, value)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(watch.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(watch.FieldUpdatedAt, field.TypeTime, value)
	}
	if wuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(watch.FieldUpdatedAt, field.TypeTime)
	}
	_node = &Watch{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{watch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
