// Code generated by ent, DO NOT EDIT.

package foreignreference

import (
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/gitbundle/store/models/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLTE(FieldID, id))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldRepoID, v))
}

// LocalIndex applies equality check predicate on the "local_index" field. It's identical to LocalIndexEQ.
func LocalIndex(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldLocalIndex, v))
}

// ForeignIndex applies equality check predicate on the "foreign_index" field. It's identical to ForeignIndexEQ.
func ForeignIndex(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldForeignIndex, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldType, v))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLTE(FieldRepoID, v))
}

// RepoIDIsNil applies the IsNil predicate on the "repo_id" field.
func RepoIDIsNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIsNull(FieldRepoID))
}

// RepoIDNotNil applies the NotNil predicate on the "repo_id" field.
func RepoIDNotNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotNull(FieldRepoID))
}

// LocalIndexEQ applies the EQ predicate on the "local_index" field.
func LocalIndexEQ(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldLocalIndex, v))
}

// LocalIndexNEQ applies the NEQ predicate on the "local_index" field.
func LocalIndexNEQ(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNEQ(FieldLocalIndex, v))
}

// LocalIndexIn applies the In predicate on the "local_index" field.
func LocalIndexIn(vs ...int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIn(FieldLocalIndex, vs...))
}

// LocalIndexNotIn applies the NotIn predicate on the "local_index" field.
func LocalIndexNotIn(vs ...int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotIn(FieldLocalIndex, vs...))
}

// LocalIndexGT applies the GT predicate on the "local_index" field.
func LocalIndexGT(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGT(FieldLocalIndex, v))
}

// LocalIndexGTE applies the GTE predicate on the "local_index" field.
func LocalIndexGTE(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGTE(FieldLocalIndex, v))
}

// LocalIndexLT applies the LT predicate on the "local_index" field.
func LocalIndexLT(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLT(FieldLocalIndex, v))
}

// LocalIndexLTE applies the LTE predicate on the "local_index" field.
func LocalIndexLTE(v int64) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLTE(FieldLocalIndex, v))
}

// LocalIndexIsNil applies the IsNil predicate on the "local_index" field.
func LocalIndexIsNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIsNull(FieldLocalIndex))
}

// LocalIndexNotNil applies the NotNil predicate on the "local_index" field.
func LocalIndexNotNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotNull(FieldLocalIndex))
}

// ForeignIndexEQ applies the EQ predicate on the "foreign_index" field.
func ForeignIndexEQ(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldForeignIndex, v))
}

// ForeignIndexNEQ applies the NEQ predicate on the "foreign_index" field.
func ForeignIndexNEQ(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNEQ(FieldForeignIndex, v))
}

// ForeignIndexIn applies the In predicate on the "foreign_index" field.
func ForeignIndexIn(vs ...string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIn(FieldForeignIndex, vs...))
}

// ForeignIndexNotIn applies the NotIn predicate on the "foreign_index" field.
func ForeignIndexNotIn(vs ...string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotIn(FieldForeignIndex, vs...))
}

// ForeignIndexGT applies the GT predicate on the "foreign_index" field.
func ForeignIndexGT(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGT(FieldForeignIndex, v))
}

// ForeignIndexGTE applies the GTE predicate on the "foreign_index" field.
func ForeignIndexGTE(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGTE(FieldForeignIndex, v))
}

// ForeignIndexLT applies the LT predicate on the "foreign_index" field.
func ForeignIndexLT(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLT(FieldForeignIndex, v))
}

// ForeignIndexLTE applies the LTE predicate on the "foreign_index" field.
func ForeignIndexLTE(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLTE(FieldForeignIndex, v))
}

// ForeignIndexContains applies the Contains predicate on the "foreign_index" field.
func ForeignIndexContains(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldContains(FieldForeignIndex, v))
}

// ForeignIndexHasPrefix applies the HasPrefix predicate on the "foreign_index" field.
func ForeignIndexHasPrefix(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldHasPrefix(FieldForeignIndex, v))
}

// ForeignIndexHasSuffix applies the HasSuffix predicate on the "foreign_index" field.
func ForeignIndexHasSuffix(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldHasSuffix(FieldForeignIndex, v))
}

// ForeignIndexIsNil applies the IsNil predicate on the "foreign_index" field.
func ForeignIndexIsNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIsNull(FieldForeignIndex))
}

// ForeignIndexNotNil applies the NotNil predicate on the "foreign_index" field.
func ForeignIndexNotNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotNull(FieldForeignIndex))
}

// ForeignIndexEqualFold applies the EqualFold predicate on the "foreign_index" field.
func ForeignIndexEqualFold(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEqualFold(FieldForeignIndex, v))
}

// ForeignIndexContainsFold applies the ContainsFold predicate on the "foreign_index" field.
func ForeignIndexContainsFold(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldContainsFold(FieldForeignIndex, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.ForeignReference {
	return predicate.ForeignReference(sql.FieldContainsFold(FieldType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ForeignReference) predicate.ForeignReference {
	return predicate.ForeignReference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ForeignReference) predicate.ForeignReference {
	return predicate.ForeignReference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ForeignReference) predicate.ForeignReference {
	return predicate.ForeignReference(sql.NotPredicates(p))
}
