// Code generated by ent, DO NOT EDIT.

package webhook

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the webhook type in the database.
	Label = "webhook"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldIsSystemWebhook holds the string denoting the is_system_webhook field in the database.
	FieldIsSystemWebhook = "is_system_webhook"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldHTTPMethod holds the string denoting the http_method field in the database.
	FieldHTTPMethod = "http_method"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldEvents holds the string denoting the events field in the database.
	FieldEvents = "events"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the webhook in the database.
	Table = "webhooks"
)

// Columns holds all SQL columns for webhook fields.
var Columns = []string{
	FieldID,
	FieldRepoID,
	FieldOrgID,
	FieldIsSystemWebhook,
	FieldURL,
	FieldHTTPMethod,
	FieldContentType,
	FieldSecret,
	FieldEvents,
	FieldIsActive,
	FieldType,
	FieldMeta,
	FieldLastStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// HTTPMethodValidator is a validator for the "http_method" field. It is called by the builders before save.
	HTTPMethodValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Webhook queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoID orders the results by the repo_id field.
func ByRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoID, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByIsSystemWebhook orders the results by the is_system_webhook field.
func ByIsSystemWebhook(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSystemWebhook, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByHTTPMethod orders the results by the http_method field.
func ByHTTPMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPMethod, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// BySecret orders the results by the secret field.
func BySecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecret, opts...).ToFunc()
}

// ByEvents orders the results by the events field.
func ByEvents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvents, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByMeta orders the results by the meta field.
func ByMeta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeta, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
