// Code generated by ent, DO NOT EDIT.

package repoindexerstatus

import (
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/store/models/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLTE(FieldID, id))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldRepoID, v))
}

// CommitSha applies equality check predicate on the "commit_sha" field. It's identical to CommitShaEQ.
func CommitSha(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldCommitSha, v))
}

// IndexerType applies equality check predicate on the "indexer_type" field. It's identical to IndexerTypeEQ.
func IndexerType(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldIndexerType, v))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v int64) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLTE(FieldRepoID, v))
}

// RepoIDIsNil applies the IsNil predicate on the "repo_id" field.
func RepoIDIsNil() predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIsNull(FieldRepoID))
}

// RepoIDNotNil applies the NotNil predicate on the "repo_id" field.
func RepoIDNotNil() predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotNull(FieldRepoID))
}

// CommitShaEQ applies the EQ predicate on the "commit_sha" field.
func CommitShaEQ(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldCommitSha, v))
}

// CommitShaNEQ applies the NEQ predicate on the "commit_sha" field.
func CommitShaNEQ(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNEQ(FieldCommitSha, v))
}

// CommitShaIn applies the In predicate on the "commit_sha" field.
func CommitShaIn(vs ...string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIn(FieldCommitSha, vs...))
}

// CommitShaNotIn applies the NotIn predicate on the "commit_sha" field.
func CommitShaNotIn(vs ...string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotIn(FieldCommitSha, vs...))
}

// CommitShaGT applies the GT predicate on the "commit_sha" field.
func CommitShaGT(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGT(FieldCommitSha, v))
}

// CommitShaGTE applies the GTE predicate on the "commit_sha" field.
func CommitShaGTE(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGTE(FieldCommitSha, v))
}

// CommitShaLT applies the LT predicate on the "commit_sha" field.
func CommitShaLT(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLT(FieldCommitSha, v))
}

// CommitShaLTE applies the LTE predicate on the "commit_sha" field.
func CommitShaLTE(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLTE(FieldCommitSha, v))
}

// CommitShaContains applies the Contains predicate on the "commit_sha" field.
func CommitShaContains(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldContains(FieldCommitSha, v))
}

// CommitShaHasPrefix applies the HasPrefix predicate on the "commit_sha" field.
func CommitShaHasPrefix(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldHasPrefix(FieldCommitSha, v))
}

// CommitShaHasSuffix applies the HasSuffix predicate on the "commit_sha" field.
func CommitShaHasSuffix(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldHasSuffix(FieldCommitSha, v))
}

// CommitShaIsNil applies the IsNil predicate on the "commit_sha" field.
func CommitShaIsNil() predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIsNull(FieldCommitSha))
}

// CommitShaNotNil applies the NotNil predicate on the "commit_sha" field.
func CommitShaNotNil() predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotNull(FieldCommitSha))
}

// CommitShaEqualFold applies the EqualFold predicate on the "commit_sha" field.
func CommitShaEqualFold(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEqualFold(FieldCommitSha, v))
}

// CommitShaContainsFold applies the ContainsFold predicate on the "commit_sha" field.
func CommitShaContainsFold(v string) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldContainsFold(FieldCommitSha, v))
}

// IndexerTypeEQ applies the EQ predicate on the "indexer_type" field.
func IndexerTypeEQ(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldEQ(FieldIndexerType, v))
}

// IndexerTypeNEQ applies the NEQ predicate on the "indexer_type" field.
func IndexerTypeNEQ(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNEQ(FieldIndexerType, v))
}

// IndexerTypeIn applies the In predicate on the "indexer_type" field.
func IndexerTypeIn(vs ...int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldIn(FieldIndexerType, vs...))
}

// IndexerTypeNotIn applies the NotIn predicate on the "indexer_type" field.
func IndexerTypeNotIn(vs ...int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldNotIn(FieldIndexerType, vs...))
}

// IndexerTypeGT applies the GT predicate on the "indexer_type" field.
func IndexerTypeGT(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGT(FieldIndexerType, v))
}

// IndexerTypeGTE applies the GTE predicate on the "indexer_type" field.
func IndexerTypeGTE(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldGTE(FieldIndexerType, v))
}

// IndexerTypeLT applies the LT predicate on the "indexer_type" field.
func IndexerTypeLT(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLT(FieldIndexerType, v))
}

// IndexerTypeLTE applies the LTE predicate on the "indexer_type" field.
func IndexerTypeLTE(v int) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.FieldLTE(FieldIndexerType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepoIndexerStatus) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepoIndexerStatus) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepoIndexerStatus) predicate.RepoIndexerStatus {
	return predicate.RepoIndexerStatus(sql.NotPredicates(p))
}
