// Code generated by ent, DO NOT EDIT.

package gpgkeyimport

import (
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/pkg/store/models/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLTE(FieldID, id))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldKeyID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldContent, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldContainsFold(FieldKeyID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.FieldContainsFold(FieldContent, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GpgKeyImport) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GpgKeyImport) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GpgKeyImport) predicate.GpgKeyImport {
	return predicate.GpgKeyImport(sql.NotPredicates(p))
}
