// Code generated by ent, DO NOT EDIT.

package label

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/store/models/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldID, id))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldRepoID, v))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldOrgID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldDescription, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldColor, v))
}

// NumIssues applies equality check predicate on the "num_issues" field. It's identical to NumIssuesEQ.
func NumIssues(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldNumIssues, v))
}

// NumClosedIssues applies equality check predicate on the "num_closed_issues" field. It's identical to NumClosedIssuesEQ.
func NumClosedIssues(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldNumClosedIssues, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v int64) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v int64) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldRepoID, v))
}

// RepoIDIsNil applies the IsNil predicate on the "repo_id" field.
func RepoIDIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldRepoID))
}

// RepoIDNotNil applies the NotNil predicate on the "repo_id" field.
func RepoIDNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldRepoID))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v int64) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v int64) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldOrgID, v))
}

// OrgIDIsNil applies the IsNil predicate on the "org_id" field.
func OrgIDIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldOrgID))
}

// OrgIDNotNil applies the NotNil predicate on the "org_id" field.
func OrgIDNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldOrgID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Label {
	return predicate.Label(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Label {
	return predicate.Label(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Label {
	return predicate.Label(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Label {
	return predicate.Label(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Label {
	return predicate.Label(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Label {
	return predicate.Label(sql.FieldContainsFold(FieldDescription, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.Label {
	return predicate.Label(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.Label {
	return predicate.Label(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.Label {
	return predicate.Label(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.Label {
	return predicate.Label(sql.FieldContainsFold(FieldColor, v))
}

// NumIssuesEQ applies the EQ predicate on the "num_issues" field.
func NumIssuesEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldNumIssues, v))
}

// NumIssuesNEQ applies the NEQ predicate on the "num_issues" field.
func NumIssuesNEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldNumIssues, v))
}

// NumIssuesIn applies the In predicate on the "num_issues" field.
func NumIssuesIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldNumIssues, vs...))
}

// NumIssuesNotIn applies the NotIn predicate on the "num_issues" field.
func NumIssuesNotIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldNumIssues, vs...))
}

// NumIssuesGT applies the GT predicate on the "num_issues" field.
func NumIssuesGT(v int64) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldNumIssues, v))
}

// NumIssuesGTE applies the GTE predicate on the "num_issues" field.
func NumIssuesGTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldNumIssues, v))
}

// NumIssuesLT applies the LT predicate on the "num_issues" field.
func NumIssuesLT(v int64) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldNumIssues, v))
}

// NumIssuesLTE applies the LTE predicate on the "num_issues" field.
func NumIssuesLTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldNumIssues, v))
}

// NumIssuesIsNil applies the IsNil predicate on the "num_issues" field.
func NumIssuesIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldNumIssues))
}

// NumIssuesNotNil applies the NotNil predicate on the "num_issues" field.
func NumIssuesNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldNumIssues))
}

// NumClosedIssuesEQ applies the EQ predicate on the "num_closed_issues" field.
func NumClosedIssuesEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldNumClosedIssues, v))
}

// NumClosedIssuesNEQ applies the NEQ predicate on the "num_closed_issues" field.
func NumClosedIssuesNEQ(v int64) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldNumClosedIssues, v))
}

// NumClosedIssuesIn applies the In predicate on the "num_closed_issues" field.
func NumClosedIssuesIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldNumClosedIssues, vs...))
}

// NumClosedIssuesNotIn applies the NotIn predicate on the "num_closed_issues" field.
func NumClosedIssuesNotIn(vs ...int64) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldNumClosedIssues, vs...))
}

// NumClosedIssuesGT applies the GT predicate on the "num_closed_issues" field.
func NumClosedIssuesGT(v int64) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldNumClosedIssues, v))
}

// NumClosedIssuesGTE applies the GTE predicate on the "num_closed_issues" field.
func NumClosedIssuesGTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldNumClosedIssues, v))
}

// NumClosedIssuesLT applies the LT predicate on the "num_closed_issues" field.
func NumClosedIssuesLT(v int64) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldNumClosedIssues, v))
}

// NumClosedIssuesLTE applies the LTE predicate on the "num_closed_issues" field.
func NumClosedIssuesLTE(v int64) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldNumClosedIssues, v))
}

// NumClosedIssuesIsNil applies the IsNil predicate on the "num_closed_issues" field.
func NumClosedIssuesIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldNumClosedIssues))
}

// NumClosedIssuesNotNil applies the NotNil predicate on the "num_closed_issues" field.
func NumClosedIssuesNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldNumClosedIssues))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Label {
	return predicate.Label(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Label {
	return predicate.Label(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Label {
	return predicate.Label(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Label {
	return predicate.Label(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Label {
	return predicate.Label(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Label) predicate.Label {
	return predicate.Label(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Label) predicate.Label {
	return predicate.Label(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Label) predicate.Label {
	return predicate.Label(sql.NotPredicates(p))
}
