// Code generated by ent, DO NOT EDIT.

package foreignreference

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the foreignreference type in the database.
	Label = "foreign_reference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldLocalIndex holds the string denoting the local_index field in the database.
	FieldLocalIndex = "local_index"
	// FieldForeignIndex holds the string denoting the foreign_index field in the database.
	FieldForeignIndex = "foreign_index"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// Table holds the table name of the foreignreference in the database.
	Table = "foreign_references"
)

// Columns holds all SQL columns for foreignreference fields.
var Columns = []string{
	FieldID,
	FieldRepoID,
	FieldLocalIndex,
	FieldForeignIndex,
	FieldType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ForeignIndexValidator is a validator for the "foreign_index" field. It is called by the builders before save.
	ForeignIndexValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
)

// OrderOption defines the ordering options for the ForeignReference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoID orders the results by the repo_id field.
func ByRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoID, opts...).ToFunc()
}

// ByLocalIndex orders the results by the local_index field.
func ByLocalIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalIndex, opts...).ToFunc()
}

// ByForeignIndex orders the results by the foreign_index field.
func ByForeignIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForeignIndex, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}
