// Code generated by ent, DO NOT EDIT.

package gpgkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gpgkey type in the database.
	Label = "gpg_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldKeyID holds the string denoting the key_id field in the database.
	FieldKeyID = "key_id"
	// FieldPrimaryKeyID holds the string denoting the primary_key_id field in the database.
	FieldPrimaryKeyID = "primary_key_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiredAt holds the string denoting the expired_at field in the database.
	FieldExpiredAt = "expired_at"
	// FieldEmails holds the string denoting the emails field in the database.
	FieldEmails = "emails"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldCanSign holds the string denoting the can_sign field in the database.
	FieldCanSign = "can_sign"
	// FieldCanEncryptComms holds the string denoting the can_encrypt_comms field in the database.
	FieldCanEncryptComms = "can_encrypt_comms"
	// FieldCanEncryptStorage holds the string denoting the can_encrypt_storage field in the database.
	FieldCanEncryptStorage = "can_encrypt_storage"
	// FieldCanCertify holds the string denoting the can_certify field in the database.
	FieldCanCertify = "can_certify"
	// Table holds the table name of the gpgkey in the database.
	Table = "gpg_keys"
)

// Columns holds all SQL columns for gpgkey fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldKeyID,
	FieldPrimaryKeyID,
	FieldContent,
	FieldCreatedAt,
	FieldExpiredAt,
	FieldEmails,
	FieldVerified,
	FieldCanSign,
	FieldCanEncryptComms,
	FieldCanEncryptStorage,
	FieldCanCertify,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	KeyIDValidator func(string) error
	// PrimaryKeyIDValidator is a validator for the "primary_key_id" field. It is called by the builders before save.
	PrimaryKeyIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
)

// OrderOption defines the ordering options for the GpgKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByKeyID orders the results by the key_id field.
func ByKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyID, opts...).ToFunc()
}

// ByPrimaryKeyID orders the results by the primary_key_id field.
func ByPrimaryKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryKeyID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiredAt orders the results by the expired_at field.
func ByExpiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredAt, opts...).ToFunc()
}

// ByEmails orders the results by the emails field.
func ByEmails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmails, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByCanSign orders the results by the can_sign field.
func ByCanSign(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanSign, opts...).ToFunc()
}

// ByCanEncryptComms orders the results by the can_encrypt_comms field.
func ByCanEncryptComms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanEncryptComms, opts...).ToFunc()
}

// ByCanEncryptStorage orders the results by the can_encrypt_storage field.
func ByCanEncryptStorage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanEncryptStorage, opts...).ToFunc()
}

// ByCanCertify orders the results by the can_certify field.
func ByCanCertify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanCertify, opts...).ToFunc()
}
