// Code generated by ent, DO NOT EDIT.

package protectedtag

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the protectedtag type in the database.
	Label = "protected_tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldNamePattern holds the string denoting the name_pattern field in the database.
	FieldNamePattern = "name_pattern"
	// FieldAllowlistUserIDs holds the string denoting the allowlist_user_i_ds field in the database.
	FieldAllowlistUserIDs = "allowlist_user_i_ds"
	// FieldAllowlistTeamIDs holds the string denoting the allowlist_team_i_ds field in the database.
	FieldAllowlistTeamIDs = "allowlist_team_i_ds"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the protectedtag in the database.
	Table = "protected_tags"
)

// Columns holds all SQL columns for protectedtag fields.
var Columns = []string{
	FieldID,
	FieldRepoID,
	FieldNamePattern,
	FieldAllowlistUserIDs,
	FieldAllowlistTeamIDs,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NamePatternValidator is a validator for the "name_pattern" field. It is called by the builders before save.
	NamePatternValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProtectedTag queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoID orders the results by the repo_id field.
func ByRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoID, opts...).ToFunc()
}

// ByNamePattern orders the results by the name_pattern field.
func ByNamePattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamePattern, opts...).ToFunc()
}

// ByAllowlistUserIDs orders the results by the allowlist_user_i_ds field.
func ByAllowlistUserIDs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowlistUserIDs, opts...).ToFunc()
}

// ByAllowlistTeamIDs orders the results by the allowlist_team_i_ds field.
func ByAllowlistTeamIDs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowlistTeamIDs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
