// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/gitbundle/storage/database/models/commitstatus"
)

// CommitStatusCreate is the builder for creating a CommitStatus entity.
type CommitStatusCreate struct {
	config
	mutation *CommitStatusMutation
	hooks    []Hook
}

// SetIndex sets the "index" field.
func (csc *CommitStatusCreate) SetIndex(i int64) *CommitStatusCreate {
	csc.mutation.SetIndex(i)
	return csc
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableIndex(i *int64) *CommitStatusCreate {
	if i != nil {
		csc.SetIndex(*i)
	}
	return csc
}

// SetRepoID sets the "repo_id" field.
func (csc *CommitStatusCreate) SetRepoID(i int64) *CommitStatusCreate {
	csc.mutation.SetRepoID(i)
	return csc
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableRepoID(i *int64) *CommitStatusCreate {
	if i != nil {
		csc.SetRepoID(*i)
	}
	return csc
}

// SetState sets the "state" field.
func (csc *CommitStatusCreate) SetState(s string) *CommitStatusCreate {
	csc.mutation.SetState(s)
	return csc
}

// SetSha sets the "sha" field.
func (csc *CommitStatusCreate) SetSha(s string) *CommitStatusCreate {
	csc.mutation.SetSha(s)
	return csc
}

// SetTargetURL sets the "target_url" field.
func (csc *CommitStatusCreate) SetTargetURL(s string) *CommitStatusCreate {
	csc.mutation.SetTargetURL(s)
	return csc
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableTargetURL(s *string) *CommitStatusCreate {
	if s != nil {
		csc.SetTargetURL(*s)
	}
	return csc
}

// SetDescription sets the "description" field.
func (csc *CommitStatusCreate) SetDescription(s string) *CommitStatusCreate {
	csc.mutation.SetDescription(s)
	return csc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableDescription(s *string) *CommitStatusCreate {
	if s != nil {
		csc.SetDescription(*s)
	}
	return csc
}

// SetContextHash sets the "context_hash" field.
func (csc *CommitStatusCreate) SetContextHash(s string) *CommitStatusCreate {
	csc.mutation.SetContextHash(s)
	return csc
}

// SetContext sets the "context" field.
func (csc *CommitStatusCreate) SetContext(s string) *CommitStatusCreate {
	csc.mutation.SetContext(s)
	return csc
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableContext(s *string) *CommitStatusCreate {
	if s != nil {
		csc.SetContext(*s)
	}
	return csc
}

// SetCreatorID sets the "creator_id" field.
func (csc *CommitStatusCreate) SetCreatorID(i int64) *CommitStatusCreate {
	csc.mutation.SetCreatorID(i)
	return csc
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableCreatorID(i *int64) *CommitStatusCreate {
	if i != nil {
		csc.SetCreatorID(*i)
	}
	return csc
}

// SetCreatedAt sets the "created_at" field.
func (csc *CommitStatusCreate) SetCreatedAt(t time.Time) *CommitStatusCreate {
	csc.mutation.SetCreatedAt(t)
	return csc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableCreatedAt(t *time.Time) *CommitStatusCreate {
	if t != nil {
		csc.SetCreatedAt(*t)
	}
	return csc
}

// SetUpdatedAt sets the "updated_at" field.
func (csc *CommitStatusCreate) SetUpdatedAt(t time.Time) *CommitStatusCreate {
	csc.mutation.SetUpdatedAt(t)
	return csc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (csc *CommitStatusCreate) SetNillableUpdatedAt(t *time.Time) *CommitStatusCreate {
	if t != nil {
		csc.SetUpdatedAt(*t)
	}
	return csc
}

// Mutation returns the CommitStatusMutation object of the builder.
func (csc *CommitStatusCreate) Mutation() *CommitStatusMutation {
	return csc.mutation
}

// Save creates the CommitStatus in the database.
func (csc *CommitStatusCreate) Save(ctx context.Context) (*CommitStatus, error) {
	csc.defaults()
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *CommitStatusCreate) SaveX(ctx context.Context) *CommitStatus {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *CommitStatusCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *CommitStatusCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csc *CommitStatusCreate) defaults() {
	if _, ok := csc.mutation.CreatedAt(); !ok {
		v := commitstatus.DefaultCreatedAt()
		csc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *CommitStatusCreate) check() error {
	if _, ok := csc.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`models: missing required field "CommitStatus.state"`)}
	}
	if v, ok := csc.mutation.State(); ok {
		if err := commitstatus.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`models: validator failed for field "CommitStatus.state": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Sha(); !ok {
		return &ValidationError{Name: "sha", err: errors.New(`models: missing required field "CommitStatus.sha"`)}
	}
	if v, ok := csc.mutation.Sha(); ok {
		if err := commitstatus.ShaValidator(v); err != nil {
			return &ValidationError{Name: "sha", err: fmt.Errorf(`models: validator failed for field "CommitStatus.sha": %w`, err)}
		}
	}
	if _, ok := csc.mutation.ContextHash(); !ok {
		return &ValidationError{Name: "context_hash", err: errors.New(`models: missing required field "CommitStatus.context_hash"`)}
	}
	if v, ok := csc.mutation.ContextHash(); ok {
		if err := commitstatus.ContextHashValidator(v); err != nil {
			return &ValidationError{Name: "context_hash", err: fmt.Errorf(`models: validator failed for field "CommitStatus.context_hash": %w`, err)}
		}
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`models: missing required field "CommitStatus.created_at"`)}
	}
	return nil
}

func (csc *CommitStatusCreate) sqlSave(ctx context.Context) (*CommitStatus, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *CommitStatusCreate) createSpec() (*CommitStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &CommitStatus{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(commitstatus.Table, sqlgraph.NewFieldSpec(commitstatus.FieldID, field.TypeInt))
	)
	if value, ok := csc.mutation.Index(); ok {
		_spec.SetField(commitstatus.FieldIndex, field.TypeInt64, value)
		_node.Index = value
	}
	if value, ok := csc.mutation.RepoID(); ok {
		_spec.SetField(commitstatus.FieldRepoID, field.TypeInt64, value)
		_node.RepoID = value
	}
	if value, ok := csc.mutation.State(); ok {
		_spec.SetField(commitstatus.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := csc.mutation.Sha(); ok {
		_spec.SetField(commitstatus.FieldSha, field.TypeString, value)
		_node.Sha = value
	}
	if value, ok := csc.mutation.TargetURL(); ok {
		_spec.SetField(commitstatus.FieldTargetURL, field.TypeString, value)
		_node.TargetURL = value
	}
	if value, ok := csc.mutation.Description(); ok {
		_spec.SetField(commitstatus.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := csc.mutation.ContextHash(); ok {
		_spec.SetField(commitstatus.FieldContextHash, field.TypeString, value)
		_node.ContextHash = value
	}
	if value, ok := csc.mutation.Context(); ok {
		_spec.SetField(commitstatus.FieldContext, field.TypeString, value)
		_node.Context = value
	}
	if value, ok := csc.mutation.CreatorID(); ok {
		_spec.SetField(commitstatus.FieldCreatorID, field.TypeInt64, value)
		_node.CreatorID = value
	}
	if value, ok := csc.mutation.CreatedAt(); ok {
		_spec.SetField(commitstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csc.mutation.UpdatedAt(); ok {
		_spec.SetField(commitstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CommitStatusCreateBulk is the builder for creating many CommitStatus entities in bulk.
type CommitStatusCreateBulk struct {
	config
	err      error
	builders []*CommitStatusCreate
}

// Save creates the CommitStatus entities in the database.
func (cscb *CommitStatusCreateBulk) Save(ctx context.Context) ([]*CommitStatus, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*CommitStatus, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommitStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *CommitStatusCreateBulk) SaveX(ctx context.Context) []*CommitStatus {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *CommitStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *CommitStatusCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}
