// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/gitbundle/storage/database/models/externalloginuser"
	"github.com/gitbundle/gitbundle/storage/database/models/predicate"
)

// ExternalLoginUserDelete is the builder for deleting a ExternalLoginUser entity.
type ExternalLoginUserDelete struct {
	config
	hooks    []Hook
	mutation *ExternalLoginUserMutation
}

// Where appends a list predicates to the ExternalLoginUserDelete builder.
func (elud *ExternalLoginUserDelete) Where(ps ...predicate.ExternalLoginUser) *ExternalLoginUserDelete {
	elud.mutation.Where(ps...)
	return elud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (elud *ExternalLoginUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, elud.sqlExec, elud.mutation, elud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (elud *ExternalLoginUserDelete) ExecX(ctx context.Context) int {
	n, err := elud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (elud *ExternalLoginUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalloginuser.Table, sqlgraph.NewFieldSpec(externalloginuser.FieldID, field.TypeInt))
	if ps := elud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, elud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	elud.mutation.done = true
	return affected, err
}

// ExternalLoginUserDeleteOne is the builder for deleting a single ExternalLoginUser entity.
type ExternalLoginUserDeleteOne struct {
	elud *ExternalLoginUserDelete
}

// Where appends a list predicates to the ExternalLoginUserDelete builder.
func (eludo *ExternalLoginUserDeleteOne) Where(ps ...predicate.ExternalLoginUser) *ExternalLoginUserDeleteOne {
	eludo.elud.mutation.Where(ps...)
	return eludo
}

// Exec executes the deletion query.
func (eludo *ExternalLoginUserDeleteOne) Exec(ctx context.Context) error {
	n, err := eludo.elud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalloginuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eludo *ExternalLoginUserDeleteOne) ExecX(ctx context.Context) {
	if err := eludo.Exec(ctx); err != nil {
		panic(err)
	}
}
