// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/gitbundle/storage/database/models/pkgproperty"
)

// PkgProperty is the model entity for the PkgProperty schema.
type PkgProperty struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RefType holds the value of the "ref_type" field.
	RefType int64 `json:"ref_type,omitempty"`
	// RefID holds the value of the "ref_id" field.
	RefID int64 `json:"ref_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Value holds the value of the "value" field.
	Value        string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PkgProperty) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pkgproperty.FieldID, pkgproperty.FieldRefType, pkgproperty.FieldRefID:
			values[i] = new(sql.NullInt64)
		case pkgproperty.FieldName, pkgproperty.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PkgProperty fields.
func (pp *PkgProperty) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pkgproperty.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pp.ID = int(value.Int64)
		case pkgproperty.FieldRefType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ref_type", values[i])
			} else if value.Valid {
				pp.RefType = value.Int64
			}
		case pkgproperty.FieldRefID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ref_id", values[i])
			} else if value.Valid {
				pp.RefID = value.Int64
			}
		case pkgproperty.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pp.Name = value.String
			}
		case pkgproperty.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				pp.Value = value.String
			}
		default:
			pp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the PkgProperty.
// This includes values selected through modifiers, order, etc.
func (pp *PkgProperty) GetValue(name string) (ent.Value, error) {
	return pp.selectValues.Get(name)
}

// Update returns a builder for updating this PkgProperty.
// Note that you need to call PkgProperty.Unwrap() before calling this method if this PkgProperty
// was returned from a transaction, and the transaction was committed or rolled back.
func (pp *PkgProperty) Update() *PkgPropertyUpdateOne {
	return NewPkgPropertyClient(pp.config).UpdateOne(pp)
}

// Unwrap unwraps the PkgProperty entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pp *PkgProperty) Unwrap() *PkgProperty {
	_tx, ok := pp.config.driver.(*txDriver)
	if !ok {
		panic("models: PkgProperty is not a transactional entity")
	}
	pp.config.driver = _tx.drv
	return pp
}

// String implements the fmt.Stringer.
func (pp *PkgProperty) String() string {
	var builder strings.Builder
	builder.WriteString("PkgProperty(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pp.ID))
	builder.WriteString("ref_type=")
	builder.WriteString(fmt.Sprintf("%v", pp.RefType))
	builder.WriteString(", ")
	builder.WriteString("ref_id=")
	builder.WriteString(fmt.Sprintf("%v", pp.RefID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(pp.Name)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(pp.Value)
	builder.WriteByte(')')
	return builder.String()
}

// PkgProperties is a parsable slice of PkgProperty.
type PkgProperties []*PkgProperty
