// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/gitbundle/storage/database/models/protectedtag"
)

// ProtectedTag is the model entity for the ProtectedTag schema.
type ProtectedTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID int64 `json:"repo_id,omitempty"`
	// NamePattern holds the value of the "name_pattern" field.
	NamePattern string `json:"name_pattern,omitempty"`
	// AllowlistUserIDs holds the value of the "allowlist_user_i_ds" field.
	AllowlistUserIDs string `json:"allowlist_user_i_ds,omitempty"`
	// AllowlistTeamIDs holds the value of the "allowlist_team_i_ds" field.
	AllowlistTeamIDs string `json:"allowlist_team_i_ds,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProtectedTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case protectedtag.FieldID, protectedtag.FieldRepoID:
			values[i] = new(sql.NullInt64)
		case protectedtag.FieldNamePattern, protectedtag.FieldAllowlistUserIDs, protectedtag.FieldAllowlistTeamIDs:
			values[i] = new(sql.NullString)
		case protectedtag.FieldCreatedAt, protectedtag.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProtectedTag fields.
func (pt *ProtectedTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case protectedtag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pt.ID = int(value.Int64)
		case protectedtag.FieldRepoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				pt.RepoID = value.Int64
			}
		case protectedtag.FieldNamePattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_pattern", values[i])
			} else if value.Valid {
				pt.NamePattern = value.String
			}
		case protectedtag.FieldAllowlistUserIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field allowlist_user_i_ds", values[i])
			} else if value.Valid {
				pt.AllowlistUserIDs = value.String
			}
		case protectedtag.FieldAllowlistTeamIDs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field allowlist_team_i_ds", values[i])
			} else if value.Valid {
				pt.AllowlistTeamIDs = value.String
			}
		case protectedtag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pt.CreatedAt = value.Time
			}
		case protectedtag.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pt.UpdatedAt = value.Time
			}
		default:
			pt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProtectedTag.
// This includes values selected through modifiers, order, etc.
func (pt *ProtectedTag) Value(name string) (ent.Value, error) {
	return pt.selectValues.Get(name)
}

// Update returns a builder for updating this ProtectedTag.
// Note that you need to call ProtectedTag.Unwrap() before calling this method if this ProtectedTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (pt *ProtectedTag) Update() *ProtectedTagUpdateOne {
	return NewProtectedTagClient(pt.config).UpdateOne(pt)
}

// Unwrap unwraps the ProtectedTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pt *ProtectedTag) Unwrap() *ProtectedTag {
	_tx, ok := pt.config.driver.(*txDriver)
	if !ok {
		panic("models: ProtectedTag is not a transactional entity")
	}
	pt.config.driver = _tx.drv
	return pt
}

// String implements the fmt.Stringer.
func (pt *ProtectedTag) String() string {
	var builder strings.Builder
	builder.WriteString("ProtectedTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pt.ID))
	builder.WriteString("repo_id=")
	builder.WriteString(fmt.Sprintf("%v", pt.RepoID))
	builder.WriteString(", ")
	builder.WriteString("name_pattern=")
	builder.WriteString(pt.NamePattern)
	builder.WriteString(", ")
	builder.WriteString("allowlist_user_i_ds=")
	builder.WriteString(pt.AllowlistUserIDs)
	builder.WriteString(", ")
	builder.WriteString("allowlist_team_i_ds=")
	builder.WriteString(pt.AllowlistTeamIDs)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pt.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProtectedTags is a parsable slice of ProtectedTag.
type ProtectedTags []*ProtectedTag
