// Code generated by ent, DO NOT EDIT.

package protectedbranch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/gitbundle/store/models/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldID, id))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRepoID, v))
}

// BranchName applies equality check predicate on the "branch_name" field. It's identical to BranchNameEQ.
func BranchName(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBranchName, v))
}

// CanPush applies equality check predicate on the "can_push" field. It's identical to CanPushEQ.
func CanPush(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldCanPush, v))
}

// EnableWhitelist applies equality check predicate on the "enable_whitelist" field. It's identical to EnableWhitelistEQ.
func EnableWhitelist(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableWhitelist, v))
}

// WhitelistUserIDs applies equality check predicate on the "whitelist_user_i_ds" field. It's identical to WhitelistUserIDsEQ.
func WhitelistUserIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistUserIDs, v))
}

// WhitelistTeamIDs applies equality check predicate on the "whitelist_team_i_ds" field. It's identical to WhitelistTeamIDsEQ.
func WhitelistTeamIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistTeamIDs, v))
}

// EnableMergeWhitelist applies equality check predicate on the "enable_merge_whitelist" field. It's identical to EnableMergeWhitelistEQ.
func EnableMergeWhitelist(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableMergeWhitelist, v))
}

// WhitelistDeployKeys applies equality check predicate on the "whitelist_deploy_keys" field. It's identical to WhitelistDeployKeysEQ.
func WhitelistDeployKeys(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistDeployKeys, v))
}

// MergeWhitelistUserIDs applies equality check predicate on the "merge_whitelist_user_i_ds" field. It's identical to MergeWhitelistUserIDsEQ.
func MergeWhitelistUserIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistTeamIDs applies equality check predicate on the "merge_whitelist_team_i_ds" field. It's identical to MergeWhitelistTeamIDsEQ.
func MergeWhitelistTeamIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldMergeWhitelistTeamIDs, v))
}

// EnableStatusCheck applies equality check predicate on the "enable_status_check" field. It's identical to EnableStatusCheckEQ.
func EnableStatusCheck(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableStatusCheck, v))
}

// StatusCheckContexts applies equality check predicate on the "status_check_contexts" field. It's identical to StatusCheckContextsEQ.
func StatusCheckContexts(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldStatusCheckContexts, v))
}

// EnableApprovalsWhitelist applies equality check predicate on the "enable_approvals_whitelist" field. It's identical to EnableApprovalsWhitelistEQ.
func EnableApprovalsWhitelist(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableApprovalsWhitelist, v))
}

// ApprovalsWhitelistUserIDs applies equality check predicate on the "approvals_whitelist_user_i_ds" field. It's identical to ApprovalsWhitelistUserIDsEQ.
func ApprovalsWhitelistUserIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistTeamIDs applies equality check predicate on the "approvals_whitelist_team_i_ds" field. It's identical to ApprovalsWhitelistTeamIDsEQ.
func ApprovalsWhitelistTeamIDs(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldApprovalsWhitelistTeamIDs, v))
}

// RequiredApprovals applies equality check predicate on the "required_approvals" field. It's identical to RequiredApprovalsEQ.
func RequiredApprovals(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRequiredApprovals, v))
}

// BlockOnRejectedReviews applies equality check predicate on the "block_on_rejected_reviews" field. It's identical to BlockOnRejectedReviewsEQ.
func BlockOnRejectedReviews(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnRejectedReviews, v))
}

// BlockOnOfficialReviewRequests applies equality check predicate on the "block_on_official_review_requests" field. It's identical to BlockOnOfficialReviewRequestsEQ.
func BlockOnOfficialReviewRequests(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnOfficialReviewRequests, v))
}

// BlockOnOutdatedBranch applies equality check predicate on the "block_on_outdated_branch" field. It's identical to BlockOnOutdatedBranchEQ.
func BlockOnOutdatedBranch(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnOutdatedBranch, v))
}

// DismissStaleApprovals applies equality check predicate on the "dismiss_stale_approvals" field. It's identical to DismissStaleApprovalsEQ.
func DismissStaleApprovals(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldDismissStaleApprovals, v))
}

// RequireSignedCommits applies equality check predicate on the "require_signed_commits" field. It's identical to RequireSignedCommitsEQ.
func RequireSignedCommits(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRequireSignedCommits, v))
}

// ProtectedFilePatterns applies equality check predicate on the "protected_file_patterns" field. It's identical to ProtectedFilePatternsEQ.
func ProtectedFilePatterns(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldProtectedFilePatterns, v))
}

// UnprotectedFilePatterns applies equality check predicate on the "unprotected_file_patterns" field. It's identical to UnprotectedFilePatternsEQ.
func UnprotectedFilePatterns(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldUnprotectedFilePatterns, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldRepoID, v))
}

// RepoIDIsNil applies the IsNil predicate on the "repo_id" field.
func RepoIDIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldRepoID))
}

// RepoIDNotNil applies the NotNil predicate on the "repo_id" field.
func RepoIDNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldRepoID))
}

// BranchNameEQ applies the EQ predicate on the "branch_name" field.
func BranchNameEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBranchName, v))
}

// BranchNameNEQ applies the NEQ predicate on the "branch_name" field.
func BranchNameNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldBranchName, v))
}

// BranchNameIn applies the In predicate on the "branch_name" field.
func BranchNameIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldBranchName, vs...))
}

// BranchNameNotIn applies the NotIn predicate on the "branch_name" field.
func BranchNameNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldBranchName, vs...))
}

// BranchNameGT applies the GT predicate on the "branch_name" field.
func BranchNameGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldBranchName, v))
}

// BranchNameGTE applies the GTE predicate on the "branch_name" field.
func BranchNameGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldBranchName, v))
}

// BranchNameLT applies the LT predicate on the "branch_name" field.
func BranchNameLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldBranchName, v))
}

// BranchNameLTE applies the LTE predicate on the "branch_name" field.
func BranchNameLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldBranchName, v))
}

// BranchNameContains applies the Contains predicate on the "branch_name" field.
func BranchNameContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldBranchName, v))
}

// BranchNameHasPrefix applies the HasPrefix predicate on the "branch_name" field.
func BranchNameHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldBranchName, v))
}

// BranchNameHasSuffix applies the HasSuffix predicate on the "branch_name" field.
func BranchNameHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldBranchName, v))
}

// BranchNameIsNil applies the IsNil predicate on the "branch_name" field.
func BranchNameIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldBranchName))
}

// BranchNameNotNil applies the NotNil predicate on the "branch_name" field.
func BranchNameNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldBranchName))
}

// BranchNameEqualFold applies the EqualFold predicate on the "branch_name" field.
func BranchNameEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldBranchName, v))
}

// BranchNameContainsFold applies the ContainsFold predicate on the "branch_name" field.
func BranchNameContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldBranchName, v))
}

// CanPushEQ applies the EQ predicate on the "can_push" field.
func CanPushEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldCanPush, v))
}

// CanPushNEQ applies the NEQ predicate on the "can_push" field.
func CanPushNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldCanPush, v))
}

// EnableWhitelistEQ applies the EQ predicate on the "enable_whitelist" field.
func EnableWhitelistEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableWhitelist, v))
}

// EnableWhitelistNEQ applies the NEQ predicate on the "enable_whitelist" field.
func EnableWhitelistNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldEnableWhitelist, v))
}

// WhitelistUserIDsEQ applies the EQ predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsNEQ applies the NEQ predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsIn applies the In predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldWhitelistUserIDs, vs...))
}

// WhitelistUserIDsNotIn applies the NotIn predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldWhitelistUserIDs, vs...))
}

// WhitelistUserIDsGT applies the GT predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsGTE applies the GTE predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsLT applies the LT predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsLTE applies the LTE predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsContains applies the Contains predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsHasPrefix applies the HasPrefix predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsHasSuffix applies the HasSuffix predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsIsNil applies the IsNil predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldWhitelistUserIDs))
}

// WhitelistUserIDsNotNil applies the NotNil predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldWhitelistUserIDs))
}

// WhitelistUserIDsEqualFold applies the EqualFold predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldWhitelistUserIDs, v))
}

// WhitelistUserIDsContainsFold applies the ContainsFold predicate on the "whitelist_user_i_ds" field.
func WhitelistUserIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldWhitelistUserIDs, v))
}

// WhitelistTeamIDsEQ applies the EQ predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsNEQ applies the NEQ predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsIn applies the In predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldWhitelistTeamIDs, vs...))
}

// WhitelistTeamIDsNotIn applies the NotIn predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldWhitelistTeamIDs, vs...))
}

// WhitelistTeamIDsGT applies the GT predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsGTE applies the GTE predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsLT applies the LT predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsLTE applies the LTE predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsContains applies the Contains predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsHasPrefix applies the HasPrefix predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsHasSuffix applies the HasSuffix predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsIsNil applies the IsNil predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldWhitelistTeamIDs))
}

// WhitelistTeamIDsNotNil applies the NotNil predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldWhitelistTeamIDs))
}

// WhitelistTeamIDsEqualFold applies the EqualFold predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldWhitelistTeamIDs, v))
}

// WhitelistTeamIDsContainsFold applies the ContainsFold predicate on the "whitelist_team_i_ds" field.
func WhitelistTeamIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldWhitelistTeamIDs, v))
}

// EnableMergeWhitelistEQ applies the EQ predicate on the "enable_merge_whitelist" field.
func EnableMergeWhitelistEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableMergeWhitelist, v))
}

// EnableMergeWhitelistNEQ applies the NEQ predicate on the "enable_merge_whitelist" field.
func EnableMergeWhitelistNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldEnableMergeWhitelist, v))
}

// WhitelistDeployKeysEQ applies the EQ predicate on the "whitelist_deploy_keys" field.
func WhitelistDeployKeysEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldWhitelistDeployKeys, v))
}

// WhitelistDeployKeysNEQ applies the NEQ predicate on the "whitelist_deploy_keys" field.
func WhitelistDeployKeysNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldWhitelistDeployKeys, v))
}

// MergeWhitelistUserIDsEQ applies the EQ predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsNEQ applies the NEQ predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsIn applies the In predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldMergeWhitelistUserIDs, vs...))
}

// MergeWhitelistUserIDsNotIn applies the NotIn predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldMergeWhitelistUserIDs, vs...))
}

// MergeWhitelistUserIDsGT applies the GT predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsGTE applies the GTE predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsLT applies the LT predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsLTE applies the LTE predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsContains applies the Contains predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsHasPrefix applies the HasPrefix predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsHasSuffix applies the HasSuffix predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsIsNil applies the IsNil predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldMergeWhitelistUserIDs))
}

// MergeWhitelistUserIDsNotNil applies the NotNil predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldMergeWhitelistUserIDs))
}

// MergeWhitelistUserIDsEqualFold applies the EqualFold predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistUserIDsContainsFold applies the ContainsFold predicate on the "merge_whitelist_user_i_ds" field.
func MergeWhitelistUserIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldMergeWhitelistUserIDs, v))
}

// MergeWhitelistTeamIDsEQ applies the EQ predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsNEQ applies the NEQ predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsIn applies the In predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldMergeWhitelistTeamIDs, vs...))
}

// MergeWhitelistTeamIDsNotIn applies the NotIn predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldMergeWhitelistTeamIDs, vs...))
}

// MergeWhitelistTeamIDsGT applies the GT predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsGTE applies the GTE predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsLT applies the LT predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsLTE applies the LTE predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsContains applies the Contains predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsHasPrefix applies the HasPrefix predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsHasSuffix applies the HasSuffix predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsIsNil applies the IsNil predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldMergeWhitelistTeamIDs))
}

// MergeWhitelistTeamIDsNotNil applies the NotNil predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldMergeWhitelistTeamIDs))
}

// MergeWhitelistTeamIDsEqualFold applies the EqualFold predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldMergeWhitelistTeamIDs, v))
}

// MergeWhitelistTeamIDsContainsFold applies the ContainsFold predicate on the "merge_whitelist_team_i_ds" field.
func MergeWhitelistTeamIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldMergeWhitelistTeamIDs, v))
}

// EnableStatusCheckEQ applies the EQ predicate on the "enable_status_check" field.
func EnableStatusCheckEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableStatusCheck, v))
}

// EnableStatusCheckNEQ applies the NEQ predicate on the "enable_status_check" field.
func EnableStatusCheckNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldEnableStatusCheck, v))
}

// StatusCheckContextsEQ applies the EQ predicate on the "status_check_contexts" field.
func StatusCheckContextsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldStatusCheckContexts, v))
}

// StatusCheckContextsNEQ applies the NEQ predicate on the "status_check_contexts" field.
func StatusCheckContextsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldStatusCheckContexts, v))
}

// StatusCheckContextsIn applies the In predicate on the "status_check_contexts" field.
func StatusCheckContextsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldStatusCheckContexts, vs...))
}

// StatusCheckContextsNotIn applies the NotIn predicate on the "status_check_contexts" field.
func StatusCheckContextsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldStatusCheckContexts, vs...))
}

// StatusCheckContextsGT applies the GT predicate on the "status_check_contexts" field.
func StatusCheckContextsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldStatusCheckContexts, v))
}

// StatusCheckContextsGTE applies the GTE predicate on the "status_check_contexts" field.
func StatusCheckContextsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldStatusCheckContexts, v))
}

// StatusCheckContextsLT applies the LT predicate on the "status_check_contexts" field.
func StatusCheckContextsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldStatusCheckContexts, v))
}

// StatusCheckContextsLTE applies the LTE predicate on the "status_check_contexts" field.
func StatusCheckContextsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldStatusCheckContexts, v))
}

// StatusCheckContextsContains applies the Contains predicate on the "status_check_contexts" field.
func StatusCheckContextsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldStatusCheckContexts, v))
}

// StatusCheckContextsHasPrefix applies the HasPrefix predicate on the "status_check_contexts" field.
func StatusCheckContextsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldStatusCheckContexts, v))
}

// StatusCheckContextsHasSuffix applies the HasSuffix predicate on the "status_check_contexts" field.
func StatusCheckContextsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldStatusCheckContexts, v))
}

// StatusCheckContextsIsNil applies the IsNil predicate on the "status_check_contexts" field.
func StatusCheckContextsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldStatusCheckContexts))
}

// StatusCheckContextsNotNil applies the NotNil predicate on the "status_check_contexts" field.
func StatusCheckContextsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldStatusCheckContexts))
}

// StatusCheckContextsEqualFold applies the EqualFold predicate on the "status_check_contexts" field.
func StatusCheckContextsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldStatusCheckContexts, v))
}

// StatusCheckContextsContainsFold applies the ContainsFold predicate on the "status_check_contexts" field.
func StatusCheckContextsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldStatusCheckContexts, v))
}

// EnableApprovalsWhitelistEQ applies the EQ predicate on the "enable_approvals_whitelist" field.
func EnableApprovalsWhitelistEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldEnableApprovalsWhitelist, v))
}

// EnableApprovalsWhitelistNEQ applies the NEQ predicate on the "enable_approvals_whitelist" field.
func EnableApprovalsWhitelistNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldEnableApprovalsWhitelist, v))
}

// ApprovalsWhitelistUserIDsEQ applies the EQ predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsNEQ applies the NEQ predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsIn applies the In predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldApprovalsWhitelistUserIDs, vs...))
}

// ApprovalsWhitelistUserIDsNotIn applies the NotIn predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldApprovalsWhitelistUserIDs, vs...))
}

// ApprovalsWhitelistUserIDsGT applies the GT predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsGTE applies the GTE predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsLT applies the LT predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsLTE applies the LTE predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsContains applies the Contains predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsHasPrefix applies the HasPrefix predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsHasSuffix applies the HasSuffix predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsIsNil applies the IsNil predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldApprovalsWhitelistUserIDs))
}

// ApprovalsWhitelistUserIDsNotNil applies the NotNil predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldApprovalsWhitelistUserIDs))
}

// ApprovalsWhitelistUserIDsEqualFold applies the EqualFold predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistUserIDsContainsFold applies the ContainsFold predicate on the "approvals_whitelist_user_i_ds" field.
func ApprovalsWhitelistUserIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldApprovalsWhitelistUserIDs, v))
}

// ApprovalsWhitelistTeamIDsEQ applies the EQ predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsNEQ applies the NEQ predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsIn applies the In predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldApprovalsWhitelistTeamIDs, vs...))
}

// ApprovalsWhitelistTeamIDsNotIn applies the NotIn predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldApprovalsWhitelistTeamIDs, vs...))
}

// ApprovalsWhitelistTeamIDsGT applies the GT predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsGTE applies the GTE predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsLT applies the LT predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsLTE applies the LTE predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsContains applies the Contains predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsHasPrefix applies the HasPrefix predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsHasSuffix applies the HasSuffix predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsIsNil applies the IsNil predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldApprovalsWhitelistTeamIDs))
}

// ApprovalsWhitelistTeamIDsNotNil applies the NotNil predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldApprovalsWhitelistTeamIDs))
}

// ApprovalsWhitelistTeamIDsEqualFold applies the EqualFold predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldApprovalsWhitelistTeamIDs, v))
}

// ApprovalsWhitelistTeamIDsContainsFold applies the ContainsFold predicate on the "approvals_whitelist_team_i_ds" field.
func ApprovalsWhitelistTeamIDsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldApprovalsWhitelistTeamIDs, v))
}

// RequiredApprovalsEQ applies the EQ predicate on the "required_approvals" field.
func RequiredApprovalsEQ(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRequiredApprovals, v))
}

// RequiredApprovalsNEQ applies the NEQ predicate on the "required_approvals" field.
func RequiredApprovalsNEQ(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldRequiredApprovals, v))
}

// RequiredApprovalsIn applies the In predicate on the "required_approvals" field.
func RequiredApprovalsIn(vs ...int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldRequiredApprovals, vs...))
}

// RequiredApprovalsNotIn applies the NotIn predicate on the "required_approvals" field.
func RequiredApprovalsNotIn(vs ...int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldRequiredApprovals, vs...))
}

// RequiredApprovalsGT applies the GT predicate on the "required_approvals" field.
func RequiredApprovalsGT(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldRequiredApprovals, v))
}

// RequiredApprovalsGTE applies the GTE predicate on the "required_approvals" field.
func RequiredApprovalsGTE(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldRequiredApprovals, v))
}

// RequiredApprovalsLT applies the LT predicate on the "required_approvals" field.
func RequiredApprovalsLT(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldRequiredApprovals, v))
}

// RequiredApprovalsLTE applies the LTE predicate on the "required_approvals" field.
func RequiredApprovalsLTE(v int64) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldRequiredApprovals, v))
}

// BlockOnRejectedReviewsEQ applies the EQ predicate on the "block_on_rejected_reviews" field.
func BlockOnRejectedReviewsEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnRejectedReviews, v))
}

// BlockOnRejectedReviewsNEQ applies the NEQ predicate on the "block_on_rejected_reviews" field.
func BlockOnRejectedReviewsNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldBlockOnRejectedReviews, v))
}

// BlockOnOfficialReviewRequestsEQ applies the EQ predicate on the "block_on_official_review_requests" field.
func BlockOnOfficialReviewRequestsEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnOfficialReviewRequests, v))
}

// BlockOnOfficialReviewRequestsNEQ applies the NEQ predicate on the "block_on_official_review_requests" field.
func BlockOnOfficialReviewRequestsNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldBlockOnOfficialReviewRequests, v))
}

// BlockOnOutdatedBranchEQ applies the EQ predicate on the "block_on_outdated_branch" field.
func BlockOnOutdatedBranchEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldBlockOnOutdatedBranch, v))
}

// BlockOnOutdatedBranchNEQ applies the NEQ predicate on the "block_on_outdated_branch" field.
func BlockOnOutdatedBranchNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldBlockOnOutdatedBranch, v))
}

// DismissStaleApprovalsEQ applies the EQ predicate on the "dismiss_stale_approvals" field.
func DismissStaleApprovalsEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldDismissStaleApprovals, v))
}

// DismissStaleApprovalsNEQ applies the NEQ predicate on the "dismiss_stale_approvals" field.
func DismissStaleApprovalsNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldDismissStaleApprovals, v))
}

// RequireSignedCommitsEQ applies the EQ predicate on the "require_signed_commits" field.
func RequireSignedCommitsEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldRequireSignedCommits, v))
}

// RequireSignedCommitsNEQ applies the NEQ predicate on the "require_signed_commits" field.
func RequireSignedCommitsNEQ(v bool) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldRequireSignedCommits, v))
}

// ProtectedFilePatternsEQ applies the EQ predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsNEQ applies the NEQ predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsIn applies the In predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldProtectedFilePatterns, vs...))
}

// ProtectedFilePatternsNotIn applies the NotIn predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldProtectedFilePatterns, vs...))
}

// ProtectedFilePatternsGT applies the GT predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsGTE applies the GTE predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsLT applies the LT predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsLTE applies the LTE predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsContains applies the Contains predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsHasPrefix applies the HasPrefix predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsHasSuffix applies the HasSuffix predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsIsNil applies the IsNil predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldProtectedFilePatterns))
}

// ProtectedFilePatternsNotNil applies the NotNil predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldProtectedFilePatterns))
}

// ProtectedFilePatternsEqualFold applies the EqualFold predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldProtectedFilePatterns, v))
}

// ProtectedFilePatternsContainsFold applies the ContainsFold predicate on the "protected_file_patterns" field.
func ProtectedFilePatternsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldProtectedFilePatterns, v))
}

// UnprotectedFilePatternsEQ applies the EQ predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsNEQ applies the NEQ predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsNEQ(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsIn applies the In predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldUnprotectedFilePatterns, vs...))
}

// UnprotectedFilePatternsNotIn applies the NotIn predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsNotIn(vs ...string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldUnprotectedFilePatterns, vs...))
}

// UnprotectedFilePatternsGT applies the GT predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsGT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsGTE applies the GTE predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsGTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsLT applies the LT predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsLT(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsLTE applies the LTE predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsLTE(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsContains applies the Contains predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsContains(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContains(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsHasPrefix applies the HasPrefix predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsHasPrefix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasPrefix(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsHasSuffix applies the HasSuffix predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsHasSuffix(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldHasSuffix(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsIsNil applies the IsNil predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldUnprotectedFilePatterns))
}

// UnprotectedFilePatternsNotNil applies the NotNil predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldUnprotectedFilePatterns))
}

// UnprotectedFilePatternsEqualFold applies the EqualFold predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsEqualFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEqualFold(FieldUnprotectedFilePatterns, v))
}

// UnprotectedFilePatternsContainsFold applies the ContainsFold predicate on the "unprotected_file_patterns" field.
func UnprotectedFilePatternsContainsFold(v string) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldContainsFold(FieldUnprotectedFilePatterns, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProtectedBranch) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProtectedBranch) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProtectedBranch) predicate.ProtectedBranch {
	return predicate.ProtectedBranch(sql.NotPredicates(p))
}
