// Code generated by ent, DO NOT EDIT.

package pkgblobupload

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pkgblobupload type in the database.
	Label = "pkg_blob_upload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlobUploadID holds the string denoting the blob_upload_id field in the database.
	FieldBlobUploadID = "blob_upload_id"
	// FieldBytesReceived holds the string denoting the bytes_received field in the database.
	FieldBytesReceived = "bytes_received"
	// FieldHashStateBytes holds the string denoting the hash_state_bytes field in the database.
	FieldHashStateBytes = "hash_state_bytes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the pkgblobupload in the database.
	Table = "pkg_blob_uploads"
)

// Columns holds all SQL columns for pkgblobupload fields.
var Columns = []string{
	FieldID,
	FieldBlobUploadID,
	FieldBytesReceived,
	FieldHashStateBytes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BlobUploadIDValidator is a validator for the "blob_upload_id" field. It is called by the builders before save.
	BlobUploadIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PkgBlobUpload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBlobUploadID orders the results by the blob_upload_id field.
func ByBlobUploadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobUploadID, opts...).ToFunc()
}

// ByBytesReceived orders the results by the bytes_received field.
func ByBytesReceived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytesReceived, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
