// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/pkg/store/models/emailaddress"
)

// EmailAddress is the model entity for the EmailAddress schema.
type EmailAddress struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// LowerEmail holds the value of the "lower_email" field.
	LowerEmail string `json:"lower_email,omitempty"`
	// IsActivated holds the value of the "is_activated" field.
	IsActivated bool `json:"is_activated,omitempty"`
	// IsPrimary holds the value of the "is_primary" field.
	IsPrimary    bool `json:"is_primary,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailAddress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailaddress.FieldIsActivated, emailaddress.FieldIsPrimary:
			values[i] = new(sql.NullBool)
		case emailaddress.FieldID, emailaddress.FieldUserID:
			values[i] = new(sql.NullInt64)
		case emailaddress.FieldEmail, emailaddress.FieldLowerEmail:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailAddress fields.
func (ea *EmailAddress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailaddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ea.ID = int(value.Int64)
		case emailaddress.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ea.UserID = value.Int64
			}
		case emailaddress.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				ea.Email = value.String
			}
		case emailaddress.FieldLowerEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lower_email", values[i])
			} else if value.Valid {
				ea.LowerEmail = value.String
			}
		case emailaddress.FieldIsActivated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_activated", values[i])
			} else if value.Valid {
				ea.IsActivated = value.Bool
			}
		case emailaddress.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				ea.IsPrimary = value.Bool
			}
		default:
			ea.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailAddress.
// This includes values selected through modifiers, order, etc.
func (ea *EmailAddress) Value(name string) (ent.Value, error) {
	return ea.selectValues.Get(name)
}

// Update returns a builder for updating this EmailAddress.
// Note that you need to call EmailAddress.Unwrap() before calling this method if this EmailAddress
// was returned from a transaction, and the transaction was committed or rolled back.
func (ea *EmailAddress) Update() *EmailAddressUpdateOne {
	return NewEmailAddressClient(ea.config).UpdateOne(ea)
}

// Unwrap unwraps the EmailAddress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ea *EmailAddress) Unwrap() *EmailAddress {
	_tx, ok := ea.config.driver.(*txDriver)
	if !ok {
		panic("models: EmailAddress is not a transactional entity")
	}
	ea.config.driver = _tx.drv
	return ea
}

// String implements the fmt.Stringer.
func (ea *EmailAddress) String() string {
	var builder strings.Builder
	builder.WriteString("EmailAddress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ea.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ea.UserID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(ea.Email)
	builder.WriteString(", ")
	builder.WriteString("lower_email=")
	builder.WriteString(ea.LowerEmail)
	builder.WriteString(", ")
	builder.WriteString("is_activated=")
	builder.WriteString(fmt.Sprintf("%v", ea.IsActivated))
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", ea.IsPrimary))
	builder.WriteByte(')')
	return builder.String()
}

// EmailAddresses is a parsable slice of EmailAddress.
type EmailAddresses []*EmailAddress
