// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/pkg/store/models/gpgkey"
)

// GpgKeyCreate is the builder for creating a GpgKey entity.
type GpgKeyCreate struct {
	config
	mutation *GpgKeyMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (gkc *GpgKeyCreate) SetOwnerID(i int64) *GpgKeyCreate {
	gkc.mutation.SetOwnerID(i)
	return gkc
}

// SetKeyID sets the "key_id" field.
func (gkc *GpgKeyCreate) SetKeyID(s string) *GpgKeyCreate {
	gkc.mutation.SetKeyID(s)
	return gkc
}

// SetPrimaryKeyID sets the "primary_key_id" field.
func (gkc *GpgKeyCreate) SetPrimaryKeyID(s string) *GpgKeyCreate {
	gkc.mutation.SetPrimaryKeyID(s)
	return gkc
}

// SetNillablePrimaryKeyID sets the "primary_key_id" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillablePrimaryKeyID(s *string) *GpgKeyCreate {
	if s != nil {
		gkc.SetPrimaryKeyID(*s)
	}
	return gkc
}

// SetContent sets the "content" field.
func (gkc *GpgKeyCreate) SetContent(s string) *GpgKeyCreate {
	gkc.mutation.SetContent(s)
	return gkc
}

// SetCreatedAt sets the "created_at" field.
func (gkc *GpgKeyCreate) SetCreatedAt(t time.Time) *GpgKeyCreate {
	gkc.mutation.SetCreatedAt(t)
	return gkc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableCreatedAt(t *time.Time) *GpgKeyCreate {
	if t != nil {
		gkc.SetCreatedAt(*t)
	}
	return gkc
}

// SetExpiredAt sets the "expired_at" field.
func (gkc *GpgKeyCreate) SetExpiredAt(t time.Time) *GpgKeyCreate {
	gkc.mutation.SetExpiredAt(t)
	return gkc
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableExpiredAt(t *time.Time) *GpgKeyCreate {
	if t != nil {
		gkc.SetExpiredAt(*t)
	}
	return gkc
}

// SetEmails sets the "emails" field.
func (gkc *GpgKeyCreate) SetEmails(s string) *GpgKeyCreate {
	gkc.mutation.SetEmails(s)
	return gkc
}

// SetNillableEmails sets the "emails" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableEmails(s *string) *GpgKeyCreate {
	if s != nil {
		gkc.SetEmails(*s)
	}
	return gkc
}

// SetVerified sets the "verified" field.
func (gkc *GpgKeyCreate) SetVerified(b bool) *GpgKeyCreate {
	gkc.mutation.SetVerified(b)
	return gkc
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableVerified(b *bool) *GpgKeyCreate {
	if b != nil {
		gkc.SetVerified(*b)
	}
	return gkc
}

// SetCanSign sets the "can_sign" field.
func (gkc *GpgKeyCreate) SetCanSign(b bool) *GpgKeyCreate {
	gkc.mutation.SetCanSign(b)
	return gkc
}

// SetNillableCanSign sets the "can_sign" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableCanSign(b *bool) *GpgKeyCreate {
	if b != nil {
		gkc.SetCanSign(*b)
	}
	return gkc
}

// SetCanEncryptComms sets the "can_encrypt_comms" field.
func (gkc *GpgKeyCreate) SetCanEncryptComms(b bool) *GpgKeyCreate {
	gkc.mutation.SetCanEncryptComms(b)
	return gkc
}

// SetNillableCanEncryptComms sets the "can_encrypt_comms" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableCanEncryptComms(b *bool) *GpgKeyCreate {
	if b != nil {
		gkc.SetCanEncryptComms(*b)
	}
	return gkc
}

// SetCanEncryptStorage sets the "can_encrypt_storage" field.
func (gkc *GpgKeyCreate) SetCanEncryptStorage(b bool) *GpgKeyCreate {
	gkc.mutation.SetCanEncryptStorage(b)
	return gkc
}

// SetNillableCanEncryptStorage sets the "can_encrypt_storage" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableCanEncryptStorage(b *bool) *GpgKeyCreate {
	if b != nil {
		gkc.SetCanEncryptStorage(*b)
	}
	return gkc
}

// SetCanCertify sets the "can_certify" field.
func (gkc *GpgKeyCreate) SetCanCertify(b bool) *GpgKeyCreate {
	gkc.mutation.SetCanCertify(b)
	return gkc
}

// SetNillableCanCertify sets the "can_certify" field if the given value is not nil.
func (gkc *GpgKeyCreate) SetNillableCanCertify(b *bool) *GpgKeyCreate {
	if b != nil {
		gkc.SetCanCertify(*b)
	}
	return gkc
}

// Mutation returns the GpgKeyMutation object of the builder.
func (gkc *GpgKeyCreate) Mutation() *GpgKeyMutation {
	return gkc.mutation
}

// Save creates the GpgKey in the database.
func (gkc *GpgKeyCreate) Save(ctx context.Context) (*GpgKey, error) {
	gkc.defaults()
	return withHooks(ctx, gkc.sqlSave, gkc.mutation, gkc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gkc *GpgKeyCreate) SaveX(ctx context.Context) *GpgKey {
	v, err := gkc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gkc *GpgKeyCreate) Exec(ctx context.Context) error {
	_, err := gkc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gkc *GpgKeyCreate) ExecX(ctx context.Context) {
	if err := gkc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gkc *GpgKeyCreate) defaults() {
	if _, ok := gkc.mutation.CreatedAt(); !ok {
		v := gpgkey.DefaultCreatedAt()
		gkc.mutation.SetCreatedAt(v)
	}
	if _, ok := gkc.mutation.Verified(); !ok {
		v := gpgkey.DefaultVerified
		gkc.mutation.SetVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gkc *GpgKeyCreate) check() error {
	if _, ok := gkc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`models: missing required field "GpgKey.owner_id"`)}
	}
	if _, ok := gkc.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`models: missing required field "GpgKey.key_id"`)}
	}
	if v, ok := gkc.mutation.KeyID(); ok {
		if err := gpgkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`models: validator failed for field "GpgKey.key_id": %w`, err)}
		}
	}
	if v, ok := gkc.mutation.PrimaryKeyID(); ok {
		if err := gpgkey.PrimaryKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "primary_key_id", err: fmt.Errorf(`models: validator failed for field "GpgKey.primary_key_id": %w`, err)}
		}
	}
	if _, ok := gkc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`models: missing required field "GpgKey.content"`)}
	}
	if _, ok := gkc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`models: missing required field "GpgKey.created_at"`)}
	}
	if _, ok := gkc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`models: missing required field "GpgKey.verified"`)}
	}
	return nil
}

func (gkc *GpgKeyCreate) sqlSave(ctx context.Context) (*GpgKey, error) {
	if err := gkc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gkc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gkc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gkc.mutation.id = &_node.ID
	gkc.mutation.done = true
	return _node, nil
}

func (gkc *GpgKeyCreate) createSpec() (*GpgKey, *sqlgraph.CreateSpec) {
	var (
		_node = &GpgKey{config: gkc.config}
		_spec = sqlgraph.NewCreateSpec(gpgkey.Table, sqlgraph.NewFieldSpec(gpgkey.FieldID, field.TypeInt))
	)
	if value, ok := gkc.mutation.OwnerID(); ok {
		_spec.SetField(gpgkey.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := gkc.mutation.KeyID(); ok {
		_spec.SetField(gpgkey.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := gkc.mutation.PrimaryKeyID(); ok {
		_spec.SetField(gpgkey.FieldPrimaryKeyID, field.TypeString, value)
		_node.PrimaryKeyID = value
	}
	if value, ok := gkc.mutation.Content(); ok {
		_spec.SetField(gpgkey.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := gkc.mutation.CreatedAt(); ok {
		_spec.SetField(gpgkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gkc.mutation.ExpiredAt(); ok {
		_spec.SetField(gpgkey.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := gkc.mutation.Emails(); ok {
		_spec.SetField(gpgkey.FieldEmails, field.TypeString, value)
		_node.Emails = value
	}
	if value, ok := gkc.mutation.Verified(); ok {
		_spec.SetField(gpgkey.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := gkc.mutation.CanSign(); ok {
		_spec.SetField(gpgkey.FieldCanSign, field.TypeBool, value)
		_node.CanSign = value
	}
	if value, ok := gkc.mutation.CanEncryptComms(); ok {
		_spec.SetField(gpgkey.FieldCanEncryptComms, field.TypeBool, value)
		_node.CanEncryptComms = value
	}
	if value, ok := gkc.mutation.CanEncryptStorage(); ok {
		_spec.SetField(gpgkey.FieldCanEncryptStorage, field.TypeBool, value)
		_node.CanEncryptStorage = value
	}
	if value, ok := gkc.mutation.CanCertify(); ok {
		_spec.SetField(gpgkey.FieldCanCertify, field.TypeBool, value)
		_node.CanCertify = value
	}
	return _node, _spec
}

// GpgKeyCreateBulk is the builder for creating many GpgKey entities in bulk.
type GpgKeyCreateBulk struct {
	config
	err      error
	builders []*GpgKeyCreate
}

// Save creates the GpgKey entities in the database.
func (gkcb *GpgKeyCreateBulk) Save(ctx context.Context) ([]*GpgKey, error) {
	if gkcb.err != nil {
		return nil, gkcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gkcb.builders))
	nodes := make([]*GpgKey, len(gkcb.builders))
	mutators := make([]Mutator, len(gkcb.builders))
	for i := range gkcb.builders {
		func(i int, root context.Context) {
			builder := gkcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GpgKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gkcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gkcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gkcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gkcb *GpgKeyCreateBulk) SaveX(ctx context.Context) []*GpgKey {
	v, err := gkcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gkcb *GpgKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := gkcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gkcb *GpgKeyCreateBulk) ExecX(ctx context.Context) {
	if err := gkcb.Exec(ctx); err != nil {
		panic(err)
	}
}
