// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/pkg/store/models/gpgkeyimport"
)

// GpgKeyImportCreate is the builder for creating a GpgKeyImport entity.
type GpgKeyImportCreate struct {
	config
	mutation *GpgKeyImportMutation
	hooks    []Hook
}

// SetKeyID sets the "key_id" field.
func (gkic *GpgKeyImportCreate) SetKeyID(s string) *GpgKeyImportCreate {
	gkic.mutation.SetKeyID(s)
	return gkic
}

// SetContent sets the "content" field.
func (gkic *GpgKeyImportCreate) SetContent(s string) *GpgKeyImportCreate {
	gkic.mutation.SetContent(s)
	return gkic
}

// Mutation returns the GpgKeyImportMutation object of the builder.
func (gkic *GpgKeyImportCreate) Mutation() *GpgKeyImportMutation {
	return gkic.mutation
}

// Save creates the GpgKeyImport in the database.
func (gkic *GpgKeyImportCreate) Save(ctx context.Context) (*GpgKeyImport, error) {
	return withHooks(ctx, gkic.sqlSave, gkic.mutation, gkic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gkic *GpgKeyImportCreate) SaveX(ctx context.Context) *GpgKeyImport {
	v, err := gkic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gkic *GpgKeyImportCreate) Exec(ctx context.Context) error {
	_, err := gkic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gkic *GpgKeyImportCreate) ExecX(ctx context.Context) {
	if err := gkic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gkic *GpgKeyImportCreate) check() error {
	if _, ok := gkic.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`models: missing required field "GpgKeyImport.key_id"`)}
	}
	if v, ok := gkic.mutation.KeyID(); ok {
		if err := gpgkeyimport.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`models: validator failed for field "GpgKeyImport.key_id": %w`, err)}
		}
	}
	if _, ok := gkic.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`models: missing required field "GpgKeyImport.content"`)}
	}
	return nil
}

func (gkic *GpgKeyImportCreate) sqlSave(ctx context.Context) (*GpgKeyImport, error) {
	if err := gkic.check(); err != nil {
		return nil, err
	}
	_node, _spec := gkic.createSpec()
	if err := sqlgraph.CreateNode(ctx, gkic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gkic.mutation.id = &_node.ID
	gkic.mutation.done = true
	return _node, nil
}

func (gkic *GpgKeyImportCreate) createSpec() (*GpgKeyImport, *sqlgraph.CreateSpec) {
	var (
		_node = &GpgKeyImport{config: gkic.config}
		_spec = sqlgraph.NewCreateSpec(gpgkeyimport.Table, sqlgraph.NewFieldSpec(gpgkeyimport.FieldID, field.TypeInt))
	)
	if value, ok := gkic.mutation.KeyID(); ok {
		_spec.SetField(gpgkeyimport.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := gkic.mutation.Content(); ok {
		_spec.SetField(gpgkeyimport.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// GpgKeyImportCreateBulk is the builder for creating many GpgKeyImport entities in bulk.
type GpgKeyImportCreateBulk struct {
	config
	err      error
	builders []*GpgKeyImportCreate
}

// Save creates the GpgKeyImport entities in the database.
func (gkicb *GpgKeyImportCreateBulk) Save(ctx context.Context) ([]*GpgKeyImport, error) {
	if gkicb.err != nil {
		return nil, gkicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gkicb.builders))
	nodes := make([]*GpgKeyImport, len(gkicb.builders))
	mutators := make([]Mutator, len(gkicb.builders))
	for i := range gkicb.builders {
		func(i int, root context.Context) {
			builder := gkicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GpgKeyImportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gkicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gkicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gkicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gkicb *GpgKeyImportCreateBulk) SaveX(ctx context.Context) []*GpgKeyImport {
	v, err := gkicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gkicb *GpgKeyImportCreateBulk) Exec(ctx context.Context) error {
	_, err := gkicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gkicb *GpgKeyImportCreateBulk) ExecX(ctx context.Context) {
	if err := gkicb.Exec(ctx); err != nil {
		panic(err)
	}
}
