// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitbundle/server/pkg/store/models/lfsmetaobject"
)

// LfsMetaObject is the model entity for the LfsMetaObject schema.
type LfsMetaObject struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Oid holds the value of the "oid" field.
	Oid string `json:"oid,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID int64 `json:"repo_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LfsMetaObject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lfsmetaobject.FieldID, lfsmetaobject.FieldSize, lfsmetaobject.FieldRepoID:
			values[i] = new(sql.NullInt64)
		case lfsmetaobject.FieldOid:
			values[i] = new(sql.NullString)
		case lfsmetaobject.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LfsMetaObject fields.
func (lmo *LfsMetaObject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lfsmetaobject.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lmo.ID = int(value.Int64)
		case lfsmetaobject.FieldOid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oid", values[i])
			} else if value.Valid {
				lmo.Oid = value.String
			}
		case lfsmetaobject.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				lmo.Size = value.Int64
			}
		case lfsmetaobject.FieldRepoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				lmo.RepoID = value.Int64
			}
		case lfsmetaobject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lmo.CreatedAt = value.Time
			}
		default:
			lmo.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LfsMetaObject.
// This includes values selected through modifiers, order, etc.
func (lmo *LfsMetaObject) Value(name string) (ent.Value, error) {
	return lmo.selectValues.Get(name)
}

// Update returns a builder for updating this LfsMetaObject.
// Note that you need to call LfsMetaObject.Unwrap() before calling this method if this LfsMetaObject
// was returned from a transaction, and the transaction was committed or rolled back.
func (lmo *LfsMetaObject) Update() *LfsMetaObjectUpdateOne {
	return NewLfsMetaObjectClient(lmo.config).UpdateOne(lmo)
}

// Unwrap unwraps the LfsMetaObject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lmo *LfsMetaObject) Unwrap() *LfsMetaObject {
	_tx, ok := lmo.config.driver.(*txDriver)
	if !ok {
		panic("models: LfsMetaObject is not a transactional entity")
	}
	lmo.config.driver = _tx.drv
	return lmo
}

// String implements the fmt.Stringer.
func (lmo *LfsMetaObject) String() string {
	var builder strings.Builder
	builder.WriteString("LfsMetaObject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lmo.ID))
	builder.WriteString("oid=")
	builder.WriteString(lmo.Oid)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", lmo.Size))
	builder.WriteString(", ")
	builder.WriteString("repo_id=")
	builder.WriteString(fmt.Sprintf("%v", lmo.RepoID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(lmo.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LfsMetaObjects is a parsable slice of LfsMetaObject.
type LfsMetaObjects []*LfsMetaObject
