// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/pkg/store/models/predicate"
	"github.com/gitbundle/server/pkg/store/models/repotopic"
)

// RepoTopicDelete is the builder for deleting a RepoTopic entity.
type RepoTopicDelete struct {
	config
	hooks    []Hook
	mutation *RepoTopicMutation
}

// Where appends a list predicates to the RepoTopicDelete builder.
func (rtd *RepoTopicDelete) Where(ps ...predicate.RepoTopic) *RepoTopicDelete {
	rtd.mutation.Where(ps...)
	return rtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rtd *RepoTopicDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rtd.sqlExec, rtd.mutation, rtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rtd *RepoTopicDelete) ExecX(ctx context.Context) int {
	n, err := rtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rtd *RepoTopicDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(repotopic.Table, sqlgraph.NewFieldSpec(repotopic.FieldID, field.TypeInt))
	if ps := rtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rtd.mutation.done = true
	return affected, err
}

// RepoTopicDeleteOne is the builder for deleting a single RepoTopic entity.
type RepoTopicDeleteOne struct {
	rtd *RepoTopicDelete
}

// Where appends a list predicates to the RepoTopicDelete builder.
func (rtdo *RepoTopicDeleteOne) Where(ps ...predicate.RepoTopic) *RepoTopicDeleteOne {
	rtdo.rtd.mutation.Where(ps...)
	return rtdo
}

// Exec executes the deletion query.
func (rtdo *RepoTopicDeleteOne) Exec(ctx context.Context) error {
	n, err := rtdo.rtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{repotopic.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rtdo *RepoTopicDeleteOne) ExecX(ctx context.Context) {
	if err := rtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
