// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitbundle/server/pkg/store/models/predicate"
	"github.com/gitbundle/server/pkg/store/models/repounit"
)

// RepoUnitDelete is the builder for deleting a RepoUnit entity.
type RepoUnitDelete struct {
	config
	hooks    []Hook
	mutation *RepoUnitMutation
}

// Where appends a list predicates to the RepoUnitDelete builder.
func (rud *RepoUnitDelete) Where(ps ...predicate.RepoUnit) *RepoUnitDelete {
	rud.mutation.Where(ps...)
	return rud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rud *RepoUnitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rud.sqlExec, rud.mutation, rud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rud *RepoUnitDelete) ExecX(ctx context.Context) int {
	n, err := rud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rud *RepoUnitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(repounit.Table, sqlgraph.NewFieldSpec(repounit.FieldID, field.TypeInt))
	if ps := rud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rud.mutation.done = true
	return affected, err
}

// RepoUnitDeleteOne is the builder for deleting a single RepoUnit entity.
type RepoUnitDeleteOne struct {
	rud *RepoUnitDelete
}

// Where appends a list predicates to the RepoUnitDelete builder.
func (rudo *RepoUnitDeleteOne) Where(ps ...predicate.RepoUnit) *RepoUnitDeleteOne {
	rudo.rud.mutation.Where(ps...)
	return rudo
}

// Exec executes the deletion query.
func (rudo *RepoUnitDeleteOne) Exec(ctx context.Context) error {
	n, err := rudo.rud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{repounit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rudo *RepoUnitDeleteOne) ExecX(ctx context.Context) {
	if err := rudo.Exec(ctx); err != nil {
		panic(err)
	}
}
